# DB種別
schemaspy.t=pgsql11
# DB接続情報
schemaspy.host=database
schemaspy.port=5432
schemaspy.user=postgres
schemaspy.password=postgres-password
# DB名
schemaspy.db=local
schemaspy.schema=public
# 出力先ディレクトリ
schemaspy.outputDir=/output
