# DB種別
schemaspy.t=pgsql
# DB接続情報
schemaspy.host=localhost
schemaspy.port=5432
schemaspy.user=postgres
schemaspy.password=postgres-password
# DB名
schemaspy.db=test
schemaspy.schema=public
# 出力先ディレクトリ
schemaspy.outputDir=/output
# 行数統計は pg 統計の更新タイミングで揺れるため出力しない
schemaspy.norows=true
