// Code generated by MockGen. DO NOT EDIT.
// Source: coupon_usecase.go
//
// Generated by this command:
//
//	mockgen -source=coupon_usecase.go -destination=mock/mock_coupon_usecase.go.gen.go -package=mock_coupon
//

// Package mock_coupon is a generated GoMock package.
package mock_coupon

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	coupon "go-boilerplate/internal/usecase/coupon"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ListApplicableToMyCart mocks base method.
func (m *MockUsecase) ListApplicableToMyCart(ctx context.Context, authn *auth.Authn) ([]coupon.CartCouponView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplicableToMyCart", ctx, authn)
	ret0, _ := ret[0].([]coupon.CartCouponView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApplicableToMyCart indicates an expected call of ListApplicableToMyCart.
func (mr *MockUsecaseMockRecorder) ListApplicableToMyCart(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplicableToMyCart", reflect.TypeOf((*MockUsecase)(nil).ListApplicableToMyCart), ctx, authn)
}

// ListMyCoupons mocks base method.
func (m *MockUsecase) ListMyCoupons(ctx context.Context, authn *auth.Authn) ([]coupon.CouponView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyCoupons", ctx, authn)
	ret0, _ := ret[0].([]coupon.CouponView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyCoupons indicates an expected call of ListMyCoupons.
func (mr *MockUsecaseMockRecorder) ListMyCoupons(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyCoupons", reflect.TypeOf((*MockUsecase)(nil).ListMyCoupons), ctx, authn)
}
