// Code generated by MockGen. DO NOT EDIT.
// Source: prefecture_usecase.go
//
// Generated by this command:
//
//	mockgen -source=prefecture_usecase.go -destination=mock/mock_prefecture_usecase.go.gen.go -package=mock_prefecture
//

// Package mock_prefecture is a generated GoMock package.
package mock_prefecture

import (
	context "context"
	prefecture "go-boilerplate/internal/usecase/prefecture"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ListPrefectures mocks base method.
func (m *MockUsecase) ListPrefectures(ctx context.Context) (prefecture.PrefectureDTOs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrefectures", ctx)
	ret0, _ := ret[0].(prefecture.PrefectureDTOs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrefectures indicates an expected call of ListPrefectures.
func (mr *MockUsecaseMockRecorder) ListPrefectures(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrefectures", reflect.TypeOf((*MockUsecase)(nil).ListPrefectures), ctx)
}
