// Code generated by MockGen. DO NOT EDIT.
// Source: run.go
//
// Generated by this command:
//
//	mockgen -source=run.go -destination=mock/mock_metrics.gen.go -package=mock_idempotency
//

// Package mock_idempotency is a generated GoMock package.
package mock_idempotency

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncConflict mocks base method.
func (m *MockMetrics) IncConflict(operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncConflict", operationID)
}

// IncConflict indicates an expected call of IncConflict.
func (mr *MockMetricsMockRecorder) IncConflict(operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncConflict", reflect.TypeOf((*MockMetrics)(nil).IncConflict), operationID)
}

// IncFingerprintMismatch mocks base method.
func (m *MockMetrics) IncFingerprintMismatch(operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFingerprintMismatch", operationID)
}

// IncFingerprintMismatch indicates an expected call of IncFingerprintMismatch.
func (mr *MockMetricsMockRecorder) IncFingerprintMismatch(operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFingerprintMismatch", reflect.TypeOf((*MockMetrics)(nil).IncFingerprintMismatch), operationID)
}

// IncReplay mocks base method.
func (m *MockMetrics) IncReplay(operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncReplay", operationID)
}

// IncReplay indicates an expected call of IncReplay.
func (mr *MockMetricsMockRecorder) IncReplay(operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncReplay", reflect.TypeOf((*MockMetrics)(nil).IncReplay), operationID)
}
