// Code generated by MockGen. DO NOT EDIT.
// Source: run.go
//
// Generated by this command:
//
//	mockgen -source=run.go -destination=mock/mock_run.go.gen.go -package=mock_idempotency
//

// Package mock_idempotency is a generated GoMock package.
package mock_idempotency

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncClaimFailure mocks base method.
func (m *MockMetrics) IncClaimFailure(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncClaimFailure", ctx, operationID)
}

// IncClaimFailure indicates an expected call of IncClaimFailure.
func (mr *MockMetricsMockRecorder) IncClaimFailure(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncClaimFailure", reflect.TypeOf((*MockMetrics)(nil).IncClaimFailure), ctx, operationID)
}

// IncCompleteFailure mocks base method.
func (m *MockMetrics) IncCompleteFailure(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCompleteFailure", ctx, operationID)
}

// IncCompleteFailure indicates an expected call of IncCompleteFailure.
func (mr *MockMetricsMockRecorder) IncCompleteFailure(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCompleteFailure", reflect.TypeOf((*MockMetrics)(nil).IncCompleteFailure), ctx, operationID)
}

// IncConflict mocks base method.
func (m *MockMetrics) IncConflict(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncConflict", ctx, operationID)
}

// IncConflict indicates an expected call of IncConflict.
func (mr *MockMetricsMockRecorder) IncConflict(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncConflict", reflect.TypeOf((*MockMetrics)(nil).IncConflict), ctx, operationID)
}

// IncFingerprintMismatch mocks base method.
func (m *MockMetrics) IncFingerprintMismatch(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFingerprintMismatch", ctx, operationID)
}

// IncFingerprintMismatch indicates an expected call of IncFingerprintMismatch.
func (mr *MockMetricsMockRecorder) IncFingerprintMismatch(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFingerprintMismatch", reflect.TypeOf((*MockMetrics)(nil).IncFingerprintMismatch), ctx, operationID)
}

// IncHit mocks base method.
func (m *MockMetrics) IncHit(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncHit", ctx, operationID)
}

// IncHit indicates an expected call of IncHit.
func (mr *MockMetricsMockRecorder) IncHit(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncHit", reflect.TypeOf((*MockMetrics)(nil).IncHit), ctx, operationID)
}

// IncMiss mocks base method.
func (m *MockMetrics) IncMiss(ctx context.Context, operationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncMiss", ctx, operationID)
}

// IncMiss indicates an expected call of IncMiss.
func (mr *MockMetricsMockRecorder) IncMiss(ctx, operationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncMiss", reflect.TypeOf((*MockMetrics)(nil).IncMiss), ctx, operationID)
}
