// Code generated by MockGen. DO NOT EDIT.
// Source: gc.go
//
// Generated by this command:
//
//	mockgen -source=gc.go -destination=mock/mock_gc.go.gen.go -package=mock_idempotency
//

// Package mock_idempotency is a generated GoMock package.
package mock_idempotency

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGCMetrics is a mock of GCMetrics interface.
type MockGCMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockGCMetricsMockRecorder
	isgomock struct{}
}

// MockGCMetricsMockRecorder is the mock recorder for MockGCMetrics.
type MockGCMetricsMockRecorder struct {
	mock *MockGCMetrics
}

// NewMockGCMetrics creates a new mock instance.
func NewMockGCMetrics(ctrl *gomock.Controller) *MockGCMetrics {
	mock := &MockGCMetrics{ctrl: ctrl}
	mock.recorder = &MockGCMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCMetrics) EXPECT() *MockGCMetricsMockRecorder {
	return m.recorder
}

// IncExpiredCleanup mocks base method.
func (m *MockGCMetrics) IncExpiredCleanup(ctx context.Context, count int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncExpiredCleanup", ctx, count)
}

// IncExpiredCleanup indicates an expected call of IncExpiredCleanup.
func (mr *MockGCMetricsMockRecorder) IncExpiredCleanup(ctx, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncExpiredCleanup", reflect.TypeOf((*MockGCMetrics)(nil).IncExpiredCleanup), ctx, count)
}

// IncExpiredCleanupFailure mocks base method.
func (m *MockGCMetrics) IncExpiredCleanupFailure(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncExpiredCleanupFailure", ctx)
}

// IncExpiredCleanupFailure indicates an expected call of IncExpiredCleanupFailure.
func (mr *MockGCMetricsMockRecorder) IncExpiredCleanupFailure(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncExpiredCleanupFailure", reflect.TypeOf((*MockGCMetrics)(nil).IncExpiredCleanupFailure), ctx)
}

// MockGCUsecase is a mock of GCUsecase interface.
type MockGCUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGCUsecaseMockRecorder
	isgomock struct{}
}

// MockGCUsecaseMockRecorder is the mock recorder for MockGCUsecase.
type MockGCUsecaseMockRecorder struct {
	mock *MockGCUsecase
}

// NewMockGCUsecase creates a new mock instance.
func NewMockGCUsecase(ctrl *gomock.Controller) *MockGCUsecase {
	mock := &MockGCUsecase{ctrl: ctrl}
	mock.recorder = &MockGCUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCUsecase) EXPECT() *MockGCUsecaseMockRecorder {
	return m.recorder
}

// SweepExpired mocks base method.
func (m *MockGCUsecase) SweepExpired(ctx context.Context, batchSize int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepExpired", ctx, batchSize)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepExpired indicates an expected call of SweepExpired.
func (mr *MockGCUsecaseMockRecorder) SweepExpired(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepExpired", reflect.TypeOf((*MockGCUsecase)(nil).SweepExpired), ctx, batchSize)
}
