// Code generated by MockGen. DO NOT EDIT.
// Source: product_image_gc_usecase.go
//
// Generated by this command:
//
//	mockgen -source=product_image_gc_usecase.go -destination=mock/mock_product_image_gc_usecase.go.gen.go -package=mock_product
//

// Package mock_product is a generated GoMock package.
package mock_product

import (
	context "context"
	product "go-boilerplate/internal/usecase/product"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockImageGCUsecase is a mock of ImageGCUsecase interface.
type MockImageGCUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockImageGCUsecaseMockRecorder
	isgomock struct{}
}

// MockImageGCUsecaseMockRecorder is the mock recorder for MockImageGCUsecase.
type MockImageGCUsecaseMockRecorder struct {
	mock *MockImageGCUsecase
}

// NewMockImageGCUsecase creates a new mock instance.
func NewMockImageGCUsecase(ctrl *gomock.Controller) *MockImageGCUsecase {
	mock := &MockImageGCUsecase{ctrl: ctrl}
	mock.recorder = &MockImageGCUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageGCUsecase) EXPECT() *MockImageGCUsecaseMockRecorder {
	return m.recorder
}

// SweepOrphans mocks base method.
func (m *MockImageGCUsecase) SweepOrphans(ctx context.Context, grace time.Duration, batchSize int32, dryRun bool) (product.ImageGCResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepOrphans", ctx, grace, batchSize, dryRun)
	ret0, _ := ret[0].(product.ImageGCResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepOrphans indicates an expected call of SweepOrphans.
func (mr *MockImageGCUsecaseMockRecorder) SweepOrphans(ctx, grace, batchSize, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepOrphans", reflect.TypeOf((*MockImageGCUsecase)(nil).SweepOrphans), ctx, grace, batchSize, dryRun)
}
