// Code generated by MockGen. DO NOT EDIT.
// Source: product_usecase.go
//
// Generated by this command:
//
//	mockgen -source=product_usecase.go -destination=mock/mock_product_usecase.go.gen.go -package=mock_product
//

// Package mock_product is a generated GoMock package.
package mock_product

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	product "go-boilerplate/internal/usecase/product"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CountProducts mocks base method.
func (m *MockUsecase) CountProducts(ctx context.Context, filter product.SearchFilter) (product.ProductCountView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProducts", ctx, filter)
	ret0, _ := ret[0].(product.ProductCountView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProducts indicates an expected call of CountProducts.
func (mr *MockUsecaseMockRecorder) CountProducts(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProducts", reflect.TypeOf((*MockUsecase)(nil).CountProducts), ctx, filter)
}

// CreateProduct mocks base method.
func (m *MockUsecase) CreateProduct(ctx context.Context, authn *auth.Authn, params product.CreateProductParams) (product.ProductView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, authn, params)
	ret0, _ := ret[0].(product.ProductView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockUsecaseMockRecorder) CreateProduct(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockUsecase)(nil).CreateProduct), ctx, authn, params)
}

// GetProduct mocks base method.
func (m *MockUsecase) GetProduct(ctx context.Context, id uuid.UUID) (product.ProductView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(product.ProductView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockUsecaseMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockUsecase)(nil).GetProduct), ctx, id)
}

// ListLowStockProducts mocks base method.
func (m *MockUsecase) ListLowStockProducts(ctx context.Context, authn *auth.Authn, params product.ListLowStockProductsParams) (product.ProductLowStockListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLowStockProducts", ctx, authn, params)
	ret0, _ := ret[0].(product.ProductLowStockListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLowStockProducts indicates an expected call of ListLowStockProducts.
func (mr *MockUsecaseMockRecorder) ListLowStockProducts(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLowStockProducts", reflect.TypeOf((*MockUsecase)(nil).ListLowStockProducts), ctx, authn, params)
}

// ListProducts mocks base method.
func (m *MockUsecase) ListProducts(ctx context.Context, params product.ListProductsParams) (product.ProductListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, params)
	ret0, _ := ret[0].(product.ProductListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockUsecaseMockRecorder) ListProducts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockUsecase)(nil).ListProducts), ctx, params)
}

// UpdateProduct mocks base method.
func (m *MockUsecase) UpdateProduct(ctx context.Context, authn *auth.Authn, id uuid.UUID, params product.UpdateProductParams) (product.ProductView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, authn, id, params)
	ret0, _ := ret[0].(product.ProductView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockUsecaseMockRecorder) UpdateProduct(ctx, authn, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockUsecase)(nil).UpdateProduct), ctx, authn, id, params)
}

// UpdateProductStock mocks base method.
func (m *MockUsecase) UpdateProductStock(ctx context.Context, authn *auth.Authn, id uuid.UUID, params product.UpdateProductStockParams) (product.ProductView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStock", ctx, authn, id, params)
	ret0, _ := ret[0].(product.ProductView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProductStock indicates an expected call of UpdateProductStock.
func (mr *MockUsecaseMockRecorder) UpdateProductStock(ctx, authn, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStock", reflect.TypeOf((*MockUsecase)(nil).UpdateProductStock), ctx, authn, id, params)
}

// UploadProductImage mocks base method.
func (m *MockUsecase) UploadProductImage(ctx context.Context, authn *auth.Authn, params product.UploadProductImageParams) (product.ProductImageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProductImage", ctx, authn, params)
	ret0, _ := ret[0].(product.ProductImageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadProductImage indicates an expected call of UploadProductImage.
func (mr *MockUsecaseMockRecorder) UploadProductImage(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProductImage", reflect.TypeOf((*MockUsecase)(nil).UploadProductImage), ctx, authn, params)
}
