// Code generated by MockGen. DO NOT EDIT.
// Source: product_usecase.go
//
// Generated by this command:
//
//	mockgen -source=product_usecase.go -destination=mock/mock_product_usecase.go.gen.go -package=mock_product
//

// Package mock_product is a generated GoMock package.
package mock_product

import (
	context "context"
	product "go-boilerplate/internal/usecase/product"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ListProducts mocks base method.
func (m *MockUsecase) ListProducts(ctx context.Context, params product.ListProductsParams) (*product.ProductListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, params)
	ret0, _ := ret[0].(*product.ProductListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockUsecaseMockRecorder) ListProducts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockUsecase)(nil).ListProducts), ctx, params)
}
