// Code generated by MockGen. DO NOT EDIT.
// Source: attributes.go
//
// Generated by this command:
//
//	mockgen -source=attributes.go -destination=mock/mock_attributes.go.gen.go -package=mock_aws
//

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAttributesBuilder is a mock of AttributesBuilder interface.
type MockAttributesBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockAttributesBuilderMockRecorder
	isgomock struct{}
}

// MockAttributesBuilderMockRecorder is the mock recorder for MockAttributesBuilder.
type MockAttributesBuilderMockRecorder struct {
	mock *MockAttributesBuilder
}

// NewMockAttributesBuilder creates a new mock instance.
func NewMockAttributesBuilder(ctrl *gomock.Controller) *MockAttributesBuilder {
	mock := &MockAttributesBuilder{ctrl: ctrl}
	mock.recorder = &MockAttributesBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttributesBuilder) EXPECT() *MockAttributesBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockAttributesBuilder) Build(queueARN string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", queueARN)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockAttributesBuilderMockRecorder) Build(queueARN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockAttributesBuilder)(nil).Build), queueARN)
}
