pre-commit:
  parallel: true
  commands:
    lint:
      glob: "*.go"
      run: make lint
    test:
      glob: "*.go"
      run: make test-cached
    sql-lint:
      glob: "*.sql"
      run: make sql-lint
    md-lint:
      glob: "*.md"
      run: make md-lint
    actions-lint:
      glob:
        - ".github/workflows/*.{yml,yaml}"
        - ".github/actions/**/*.{yml,yaml}"
      run: make actions-lint
    docker-lint:
      glob:
        - "docker/**/Dockerfile"
        - ".hadolint.yaml"
      run: make docker-lint
    pin-actions:
      glob:
        - ".github/workflows/*.{yml,yaml}"
        - ".github/actions/**/*.{yml,yaml}"
        - ".github/actions-pin.toml"
      run: make pin-actions-check
    migration-check-version:
      glob: "database/migrations/*.sql"
      run: make check-migration-up-version check-migration-down-version
    migration-check-gap:
      glob: "database/migrations/*.sql"
      run: make check-migration-up-gap check-migration-down-gap

commit-msg:
  commands:
    commitlint:
      run: make commitlint COMMIT_MSG_FILE={1}

pre-push:
  parallel: true
  commands:
    secret-scan:
      run: make secret-scan
    test:
      glob: "*.go"
      run: make test
    gen-go-check:
      run: make gen-bundle-oapi gen-go-code && git diff --exit-code -- '*.gen.go' '*/mock/mock_*.go' '*_mock.go' openapi/openapi.gen.yaml
    tidy-check:
      run: go mod tidy && git diff --exit-code go.mod go.sum
