pre-commit:
  parallel: true
  commands:
    lint:
      run: make lint
    test:
      run: make test
    sql-lint:
      run: make sql-lint
    migration-check-version:
      run: make check-migration-up-version check-migration-down-version
    migration-check-gap:
      run: make check-migration-up-gap check-migration-down-gap

pre-push:
  commands:
    gen-go-check:
      run: make gen-bundle-oapi gen-go-code && git diff --exit-code -- '*.gen.go' '*/mock/mock_*.go' '*_mock.go' openapi/openapi.gen.yaml
    tidy-check:
      run: go mod tidy && git diff --exit-code go.mod go.sum
