sonar.projectKey=Tomy-ch_go-boilerplate
sonar.organization=tomy-ch
sonar.projectName=go-boilerplate

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/vendor/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/src/generated/**,\
  **/*.gen.go,\
  **/*.sql.go,\
  **/*_mock.go,\
  **/openapi.gen.yaml,\
  docs/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/*.test.ts

sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=scripts/coverage/lcov.info
sonar.coverage.exclusions=scripts/**/index.ts
