// Code generated by MockGen. DO NOT EDIT.
// Source: cart_repository.go
//
// Generated by this command:
//
//	mockgen -source=cart_repository.go -destination=mock/mock_cart_repository.go.gen.go -package=mock_cart
//

// Package mock_cart is a generated GoMock package.
package mock_cart

import (
	context "context"
	cart "go-boilerplate/internal/domain/cart"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, c *cart.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, c)
}

// CreateOwnerIfAbsent mocks base method.
func (m *MockRepository) CreateOwnerIfAbsent(ctx context.Context, c *cart.Cart) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwnerIfAbsent", ctx, c)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOwnerIfAbsent indicates an expected call of CreateOwnerIfAbsent.
func (mr *MockRepositoryMockRecorder) CreateOwnerIfAbsent(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwnerIfAbsent", reflect.TypeOf((*MockRepository)(nil).CreateOwnerIfAbsent), ctx, c)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockRepository) DeleteExpired(ctx context.Context, now time.Time, limit int32) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, now, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRepositoryMockRecorder) DeleteExpired(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRepository)(nil).DeleteExpired), ctx, now, limit)
}

// FindByOwnerID mocks base method.
func (m *MockRepository) FindByOwnerID(ctx context.Context, userID uuid.UUID) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ctx, userID)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockRepositoryMockRecorder) FindByOwnerID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockRepository)(nil).FindByOwnerID), ctx, userID)
}

// FindBySessionToken mocks base method.
func (m *MockRepository) FindBySessionToken(ctx context.Context, token cart.SessionToken) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySessionToken", ctx, token)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySessionToken indicates an expected call of FindBySessionToken.
func (mr *MockRepositoryMockRecorder) FindBySessionToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySessionToken", reflect.TypeOf((*MockRepository)(nil).FindBySessionToken), ctx, token)
}

// LockByID mocks base method.
func (m *MockRepository) LockByID(ctx context.Context, id uuid.UUID) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByID", ctx, id)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByID indicates an expected call of LockByID.
func (mr *MockRepositoryMockRecorder) LockByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByID", reflect.TypeOf((*MockRepository)(nil).LockByID), ctx, id)
}

// LockByIDs mocks base method.
func (m *MockRepository) LockByIDs(ctx context.Context, ids []uuid.UUID) (cart.Carts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByIDs", ctx, ids)
	ret0, _ := ret[0].(cart.Carts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByIDs indicates an expected call of LockByIDs.
func (mr *MockRepositoryMockRecorder) LockByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByIDs", reflect.TypeOf((*MockRepository)(nil).LockByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, c *cart.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, c)
}
