// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_usecase.go
//
// Generated by this command:
//
//	mockgen -source=purchase_usecase.go -destination=mock/mock_purchase_usecase.go.gen.go -package=mock_purchase
//

// Package mock_purchase is a generated GoMock package.
package mock_purchase

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	purchase "go-boilerplate/internal/usecase/purchase"
	paging "go-boilerplate/internal/usecase/tools/paging"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CancelPurchase mocks base method.
func (m *MockUsecase) CancelPurchase(ctx context.Context, params purchase.CancelPurchaseParams) (purchase.CancelPurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPurchase", ctx, params)
	ret0, _ := ret[0].(purchase.CancelPurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPurchase indicates an expected call of CancelPurchase.
func (mr *MockUsecaseMockRecorder) CancelPurchase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPurchase", reflect.TypeOf((*MockUsecase)(nil).CancelPurchase), ctx, params)
}

// CreatePurchase mocks base method.
func (m *MockUsecase) CreatePurchase(ctx context.Context, params purchase.CreatePurchaseParams) (purchase.PurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", ctx, params)
	ret0, _ := ret[0].(purchase.PurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockUsecaseMockRecorder) CreatePurchase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockUsecase)(nil).CreatePurchase), ctx, params)
}

// DeliverPurchase mocks base method.
func (m *MockUsecase) DeliverPurchase(ctx context.Context, authn *auth.Authn, purchaseID uuid.UUID) (purchase.DeliverPurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverPurchase", ctx, authn, purchaseID)
	ret0, _ := ret[0].(purchase.DeliverPurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliverPurchase indicates an expected call of DeliverPurchase.
func (mr *MockUsecaseMockRecorder) DeliverPurchase(ctx, authn, purchaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverPurchase", reflect.TypeOf((*MockUsecase)(nil).DeliverPurchase), ctx, authn, purchaseID)
}

// GetPurchaseDetail mocks base method.
func (m *MockUsecase) GetPurchaseDetail(ctx context.Context, authn *auth.Authn, purchaseID uuid.UUID) (purchase.PurchaseGetDetailView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseDetail", ctx, authn, purchaseID)
	ret0, _ := ret[0].(purchase.PurchaseGetDetailView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseDetail indicates an expected call of GetPurchaseDetail.
func (mr *MockUsecaseMockRecorder) GetPurchaseDetail(ctx, authn, purchaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseDetail", reflect.TypeOf((*MockUsecase)(nil).GetPurchaseDetail), ctx, authn, purchaseID)
}

// GetPurchases mocks base method.
func (m *MockUsecase) GetPurchases(ctx context.Context, userID uuid.UUID, cursor *paging.Cursor) (*purchase.PurchaseListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchases", ctx, userID, cursor)
	ret0, _ := ret[0].(*purchase.PurchaseListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchases indicates an expected call of GetPurchases.
func (mr *MockUsecaseMockRecorder) GetPurchases(ctx, userID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchases", reflect.TypeOf((*MockUsecase)(nil).GetPurchases), ctx, userID, cursor)
}

// ListShippablePurchases mocks base method.
func (m *MockUsecase) ListShippablePurchases(ctx context.Context, authn *auth.Authn, params purchase.ListShippablePurchasesParams) (purchase.PurchaseShippableListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShippablePurchases", ctx, authn, params)
	ret0, _ := ret[0].(purchase.PurchaseShippableListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShippablePurchases indicates an expected call of ListShippablePurchases.
func (mr *MockUsecaseMockRecorder) ListShippablePurchases(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShippablePurchases", reflect.TypeOf((*MockUsecase)(nil).ListShippablePurchases), ctx, authn, params)
}

// PayPurchase mocks base method.
func (m *MockUsecase) PayPurchase(ctx context.Context, params purchase.PayPurchaseParams) (purchase.PayPurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayPurchase", ctx, params)
	ret0, _ := ret[0].(purchase.PayPurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayPurchase indicates an expected call of PayPurchase.
func (mr *MockUsecaseMockRecorder) PayPurchase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayPurchase", reflect.TypeOf((*MockUsecase)(nil).PayPurchase), ctx, params)
}

// ShipPurchase mocks base method.
func (m *MockUsecase) ShipPurchase(ctx context.Context, authn *auth.Authn, purchaseID uuid.UUID) (purchase.ShipPurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipPurchase", ctx, authn, purchaseID)
	ret0, _ := ret[0].(purchase.ShipPurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipPurchase indicates an expected call of ShipPurchase.
func (mr *MockUsecaseMockRecorder) ShipPurchase(ctx, authn, purchaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipPurchase", reflect.TypeOf((*MockUsecase)(nil).ShipPurchase), ctx, authn, purchaseID)
}
