// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock/mock_provider.go -package=mock_driver
//

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	driver "boilerplate-go/internal/infrastructure/rdb/driver"
	logging "boilerplate-go/internal/logging"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggingDBProvider is a mock of LoggingDBProvider interface.
type MockLoggingDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLoggingDBProviderMockRecorder
	isgomock struct{}
}

// MockLoggingDBProviderMockRecorder is the mock recorder for MockLoggingDBProvider.
type MockLoggingDBProviderMockRecorder struct {
	mock *MockLoggingDBProvider
}

// NewMockLoggingDBProvider creates a new mock instance.
func NewMockLoggingDBProvider(ctrl *gomock.Controller) *MockLoggingDBProvider {
	mock := &MockLoggingDBProvider{ctrl: ctrl}
	mock.recorder = &MockLoggingDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggingDBProvider) EXPECT() *MockLoggingDBProviderMockRecorder {
	return m.recorder
}

// NewLoggingDB mocks base method.
func (m *MockLoggingDBProvider) NewLoggingDB(ctx context.Context) driver.DBTX {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLoggingDB", ctx)
	ret0, _ := ret[0].(driver.DBTX)
	return ret0
}

// NewLoggingDB indicates an expected call of NewLoggingDB.
func (mr *MockLoggingDBProviderMockRecorder) NewLoggingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLoggingDB", reflect.TypeOf((*MockLoggingDBProvider)(nil).NewLoggingDB), ctx)
}

// logFields mocks base method.
func (m *MockLoggingDBProvider) logFields() logging.LogFields {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "logFields")
	ret0, _ := ret[0].(logging.LogFields)
	return ret0
}

// logFields indicates an expected call of logFields.
func (mr *MockLoggingDBProviderMockRecorder) logFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "logFields", reflect.TypeOf((*MockLoggingDBProvider)(nil).logFields))
}

// logger mocks base method.
func (m *MockLoggingDBProvider) logger() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "logger")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// logger indicates an expected call of logger.
func (mr *MockLoggingDBProviderMockRecorder) logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "logger", reflect.TypeOf((*MockLoggingDBProvider)(nil).logger))
}
