// Code generated by MockGen. DO NOT EDIT.
// Source: query_metric.go
//
// Generated by this command:
//
//	mockgen -source=query_metric.go -destination=mock/mock_query_metric.go.gen.go -package=mock_driver
//

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	context "context"
	driver "go-boilerplate/internal/infrastructure/rdb/driver"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueryRecorder is a mock of QueryRecorder interface.
type MockQueryRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRecorderMockRecorder
	isgomock struct{}
}

// MockQueryRecorderMockRecorder is the mock recorder for MockQueryRecorder.
type MockQueryRecorderMockRecorder struct {
	mock *MockQueryRecorder
}

// NewMockQueryRecorder creates a new mock instance.
func NewMockQueryRecorder(ctrl *gomock.Controller) *MockQueryRecorder {
	mock := &MockQueryRecorder{ctrl: ctrl}
	mock.recorder = &MockQueryRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRecorder) EXPECT() *MockQueryRecorderMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockQueryRecorder) Observe(ctx context.Context, attrs driver.QueryAttrs) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Observe", ctx, attrs)
}

// Observe indicates an expected call of Observe.
func (mr *MockQueryRecorderMockRecorder) Observe(ctx, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockQueryRecorder)(nil).Observe), ctx, attrs)
}
