// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go
//
// Generated by this command:
//
//	mockgen -source=driver.go -destination=mock/mock_driver.go -package=mock_driver
//

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseDriver is a mock of DatabaseDriver interface.
type MockDatabaseDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseDriverMockRecorder
	isgomock struct{}
}

// MockDatabaseDriverMockRecorder is the mock recorder for MockDatabaseDriver.
type MockDatabaseDriverMockRecorder struct {
	mock *MockDatabaseDriver
}

// NewMockDatabaseDriver creates a new mock instance.
func NewMockDatabaseDriver(ctrl *gomock.Controller) *MockDatabaseDriver {
	mock := &MockDatabaseDriver{ctrl: ctrl}
	mock.recorder = &MockDatabaseDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseDriver) EXPECT() *MockDatabaseDriverMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockDatabaseDriver) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockDatabaseDriverMockRecorder) ExecContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockDatabaseDriver)(nil).ExecContext), varargs...)
}

// PrepareContext mocks base method.
func (m *MockDatabaseDriver) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", ctx, query)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockDatabaseDriverMockRecorder) PrepareContext(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockDatabaseDriver)(nil).PrepareContext), ctx, query)
}

// QueryContext mocks base method.
func (m *MockDatabaseDriver) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockDatabaseDriverMockRecorder) QueryContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockDatabaseDriver)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockDatabaseDriver) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockDatabaseDriverMockRecorder) QueryRowContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockDatabaseDriver)(nil).QueryRowContext), varargs...)
}

// beginTx mocks base method.
func (m *MockDatabaseDriver) beginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "beginTx", ctx, opts)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// beginTx indicates an expected call of beginTx.
func (mr *MockDatabaseDriverMockRecorder) beginTx(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "beginTx", reflect.TypeOf((*MockDatabaseDriver)(nil).beginTx), ctx, opts)
}

// close mocks base method.
func (m *MockDatabaseDriver) close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "close")
	ret0, _ := ret[0].(error)
	return ret0
}

// close indicates an expected call of close.
func (mr *MockDatabaseDriverMockRecorder) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*MockDatabaseDriver)(nil).close))
}

// pingContext mocks base method.
func (m *MockDatabaseDriver) pingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "pingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// pingContext indicates an expected call of pingContext.
func (mr *MockDatabaseDriverMockRecorder) pingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pingContext", reflect.TypeOf((*MockDatabaseDriver)(nil).pingContext), ctx)
}
