// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_summary_usecase.go
//
// Generated by this command:
//
//	mockgen -source=purchase_summary_usecase.go -destination=mock/mock_purchase_summary_usecase.go.gen.go -package=mock_summary
//

// Package mock_summary is a generated GoMock package.
package mock_summary

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	summary "go-boilerplate/internal/usecase/purchase/summary"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetPurchaseSummary mocks base method.
func (m *MockUsecase) GetPurchaseSummary(ctx context.Context, authn *auth.Authn) (summary.SummaryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseSummary", ctx, authn)
	ret0, _ := ret[0].(summary.SummaryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseSummary indicates an expected call of GetPurchaseSummary.
func (mr *MockUsecaseMockRecorder) GetPurchaseSummary(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseSummary", reflect.TypeOf((*MockUsecase)(nil).GetPurchaseSummary), ctx, authn)
}
