// Code generated by MockGen. DO NOT EDIT.
// Source: recorder.go
//
// Generated by this command:
//
//	mockgen -source=recorder.go -destination=mock/mock_recorder.go.gen.go -package=mock_redmetrics
//

// Package mock_redmetrics is a generated GoMock package.
package mock_redmetrics

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockRecorder) Observe(method, route string, statusCode int, statusClass string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Observe", method, route, statusCode, statusClass, duration)
}

// Observe indicates an expected call of Observe.
func (mr *MockRecorderMockRecorder) Observe(method, route, statusCode, statusClass, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockRecorder)(nil).Observe), method, route, statusCode, statusClass, duration)
}
