server {
    listen 80;

    root /usr/share/nginx/html;

    include /etc/nginx/mime.types;

    types {
        application/javascript js jsx;
    }

    location /portal/ {
        try_files $uri $uri/ /portal/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
