// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=mock/mock_resolver.go.gen.go -package=mock_auth
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentityResolver is a mock of IdentityResolver interface.
type MockIdentityResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityResolverMockRecorder
	isgomock struct{}
}

// MockIdentityResolverMockRecorder is the mock recorder for MockIdentityResolver.
type MockIdentityResolverMockRecorder struct {
	mock *MockIdentityResolver
}

// NewMockIdentityResolver creates a new mock instance.
func NewMockIdentityResolver(ctrl *gomock.Controller) *MockIdentityResolver {
	mock := &MockIdentityResolver{ctrl: ctrl}
	mock.recorder = &MockIdentityResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityResolver) EXPECT() *MockIdentityResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIdentityResolver) Resolve(ctx context.Context, authn *auth.Authn) (*auth.Authn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, authn)
	ret0, _ := ret[0].(*auth.Authn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIdentityResolverMockRecorder) Resolve(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIdentityResolver)(nil).Resolve), ctx, authn)
}
