// Code generated by MockGen. DO NOT EDIT.
// Source: user_role_usecase.go
//
// Generated by this command:
//
//	mockgen -source=user_role_usecase.go -destination=mock/mock_user_role_usecase.go.gen.go -package=mock_role
//

// Package mock_role is a generated GoMock package.
package mock_role

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	role "go-boilerplate/internal/usecase/user/role"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetMyRoles mocks base method.
func (m *MockUsecase) GetMyRoles(ctx context.Context, authn *auth.Authn) (role.RolesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyRoles", ctx, authn)
	ret0, _ := ret[0].(role.RolesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyRoles indicates an expected call of GetMyRoles.
func (mr *MockUsecaseMockRecorder) GetMyRoles(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyRoles", reflect.TypeOf((*MockUsecase)(nil).GetMyRoles), ctx, authn)
}
