type: object
description: 商品に紐づくカテゴリです。
required:
  - id
  - name
properties:
  id:
    type: string
    format: uuid
    description: 商品カテゴリID
    example: "5dd52d84-78eb-4a52-ba0b-2e11c95c2af2"
  name:
    type: string
    description: 商品カテゴリ名
    example: "電子機器"
