type: object
description: 商品カテゴリマスタ 1 件分のレスポンスです。
allOf:
  - $ref: './ProductCategoryRef.yaml'
  - type: object
    description: 商品カテゴリマスタの詳細情報です。
    required:
      - code
    properties:
      code:
        type: integer
        description: 商品カテゴリコード
        example: 1
