// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	{{- if .ImportPath}}

	{{.ImportAlias}} "{{.ImportPath}}"
	{{- end}}

	"github.com/labstack/echo/v4"
)

type {{.NameLower}}KeyType struct{}

var {{.NameLower}}Key = {{.NameLower}}KeyType{}

// --- std lib context ---

func Set{{.NameCamel}}(ctx context.Context, val {{.Type}}) context.Context {
	return context.WithValue(ctx, {{.NameLower}}Key, val)
}

func Get{{.NameCamel}}(ctx context.Context) ({{.Type}}, bool) {
	val := ctx.Value({{.NameLower}}Key)
	if v, ok := val.({{.Type}}); ok {
		return v, true
	}
	return *new({{.Type}}), false
}

// --- echo.Context wrapper ---

func Set{{.NameCamel}}ToEcho(c echo.Context, val {{.Type}}) {
	ctx := context.WithValue(c.Request().Context(), {{.NameLower}}Key, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func Get{{.NameCamel}}FromEcho(c echo.Context) ({{.Type}}, bool) {
	val := c.Request().Context().Value({{.NameLower}}Key)
	if v, ok := val.({{.Type}}); ok {
		return v, true
	}
	return *new({{.Type}}), false
}
