// Code generated by gen_ctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	{{- if .ImportPath}}

	{{.ImportAlias}} "{{.ImportPath}}"
	{{- end}}

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/require"
)

func TestSet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	base := context.Background()
	ctx := context.WithValue(base, {{.NameLower}}Key, {{.TestSuccessValue}})

	val := ctx.Value({{.NameLower}}Key)
	v, ok := val.({{.Type}})
	require.True(t, ok)
	require.Equal(t, {{.TestSuccessValue}}, v)
}

func TestGet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = Set{{.NameCamel}}(ctx, {{.TestSuccessValue}})

		val, ok := Get{{.NameCamel}}(ctx)
		require.True(t, ok)
		require.Equal(t, {{.TestSuccessValue}}, val)
	})

	t.Run("standard context - no value", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := Get{{.NameCamel}}(ctx)
		require.False(t, ok)
		require.Equal(t, {{.TestFailValue}}, val)
	})
}

func TestSet{{.NameCamel}}ToEcho(t *testing.T) {
	t.Parallel()

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		Set{{.NameCamel}}ToEcho(c, {{.TestSuccessValue}})
		val, ok := Get{{.NameCamel}}FromEcho(c)

		require.True(t, ok)
		require.Equal(t, {{.TestSuccessValue}}, val)
	})

	t.Run("echo context - no value", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		val, ok := Get{{.NameCamel}}FromEcho(c)
		require.False(t, ok)
		require.Equal(t, {{.TestFailValue}}, val)
	})
}
