// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	{{- if .ImportPath}}

	{{.ImportAlias}} "{{.ImportPath}}"
	{{- end}}

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
)

func TestSet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	// Set{{.NameCamel}} が private な {{.NameLower}}Key で値を書き込むことを直接検証する
	// （Get{{.NameCamel}} には依存しない / Set/Get のテストを独立にする）。
	ctx := Set{{.NameCamel}}(context.Background(), {{.TestSuccessValue}})

	val := ctx.Value({{.NameLower}}Key)
	v, ok := val.({{.Type}})
	assert.True(t, ok)
	assert.Equal(t, {{.TestSuccessValue}}, v)
}

func TestGet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	t.Run("正常系_標準コンテキストから取得できる", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = Set{{.NameCamel}}(ctx, {{.TestSuccessValue}})

		val, ok := Get{{.NameCamel}}(ctx)
		assert.True(t, ok)
		assert.Equal(t, {{.TestSuccessValue}}, val)
	})

	t.Run("異常系_値が無い場合はfalseを返す", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := Get{{.NameCamel}}(ctx)
		assert.False(t, ok)
		assert.Equal(t, {{.TestFailValue}}, val)
	})
}

func TestSet{{.NameCamel}}ToEcho(t *testing.T) {
	t.Parallel()

	t.Run("正常系_echoへ設定し取得できる", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		Set{{.NameCamel}}ToEcho(c, {{.TestSuccessValue}})
		val, ok := Get{{.NameCamel}}FromEcho(c)

		assert.True(t, ok)
		assert.Equal(t, {{.TestSuccessValue}}, val)
	})

	t.Run("異常系_echoに値が無い場合はfalseを返す", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		val, ok := Get{{.NameCamel}}FromEcho(c)
		assert.False(t, ok)
		assert.Equal(t, {{.TestFailValue}}, val)
	})
}
