// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	{{- if .ImportPath}}

	{{.ImportAlias}} "{{.ImportPath}}"
	{{- end}}

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("privateキーへ値を書き込む", func(t *testing.T) {
			t.Parallel()
			ctx := Set{{.NameCamel}}(context.Background(), {{.TestSuccessValue}})

			v, ok := ctx.Value({{.NameLower}}Key).({{.Type}})
			require.True(t, ok)
			assert.Equal(t, {{.TestSuccessValue}}, v)
		})
	})
}

func TestGet{{.NameCamel}}(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("標準コンテキストから取得できる", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			ctx = Set{{.NameCamel}}(ctx, {{.TestSuccessValue}})

			val, ok := Get{{.NameCamel}}(ctx)
			assert.True(t, ok)
			assert.Equal(t, {{.TestSuccessValue}}, val)
		})

		t.Run("ゼロ値を設定した場合も未設定と区別してokがtrueになる", func(t *testing.T) {
			t.Parallel()
			ctx := Set{{.NameCamel}}(context.Background(), {{.TestFailValue}})

			val, ok := Get{{.NameCamel}}(ctx)
			assert.True(t, ok)
			assert.Equal(t, {{.TestFailValue}}, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			val, ok := Get{{.NameCamel}}(ctx)
			assert.False(t, ok)
			assert.Equal(t, {{.TestFailValue}}, val)
		})
	})
}

func TestSet{{.NameCamel}}ToEcho(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoへ設定し取得できる", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			Set{{.NameCamel}}ToEcho(c, {{.TestSuccessValue}})
			val, ok := Get{{.NameCamel}}FromEcho(c)

			assert.True(t, ok)
			assert.Equal(t, {{.TestSuccessValue}}, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoに値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			val, ok := Get{{.NameCamel}}FromEcho(c)
			assert.False(t, ok)
			assert.Equal(t, {{.TestFailValue}}, val)
		})
	})
}
