// Code generated by MockGen. DO NOT EDIT.
// Source: ip_rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source=ip_rate_limiter.go -destination=mock/mock_ip_rate_limiter.go -package=mock_ratelimit
//

// Package mock_ratelimit is a generated GoMock package.
package mock_ratelimit

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockIPRateLimiter is a mock of IPRateLimiter interface.
type MockIPRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockIPRateLimiterMockRecorder
	isgomock struct{}
}

// MockIPRateLimiterMockRecorder is the mock recorder for MockIPRateLimiter.
type MockIPRateLimiterMockRecorder struct {
	mock *MockIPRateLimiter
}

// NewMockIPRateLimiter creates a new mock instance.
func NewMockIPRateLimiter(ctrl *gomock.Controller) *MockIPRateLimiter {
	mock := &MockIPRateLimiter{ctrl: ctrl}
	mock.recorder = &MockIPRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPRateLimiter) EXPECT() *MockIPRateLimiterMockRecorder {
	return m.recorder
}

// AllowRequest mocks base method.
func (m *MockIPRateLimiter) AllowRequest(c echo.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowRequest", c)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowRequest indicates an expected call of AllowRequest.
func (mr *MockIPRateLimiterMockRecorder) AllowRequest(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRequest", reflect.TypeOf((*MockIPRateLimiter)(nil).AllowRequest), c)
}

// Cleanup mocks base method.
func (m *MockIPRateLimiter) Cleanup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup")
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockIPRateLimiterMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockIPRateLimiter)(nil).Cleanup))
}
