// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health_check_system_query_select_system_health.sql

package sqlc

import (
	"context"
)

const getDBHealthCheck = `-- name: GetDBHealthCheck :one
SELECT 1 AS health_check
`

func (q *Queries) GetDBHealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDBHealthCheck)
	var health_check int32
	err := row.Scan(&health_check)
	return health_check, err
}
