// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_repository_select_user_by_id.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserDomainByID = `-- name: GetUserDomainByID :one
SELECT
    u.id,
    u.first_name,
    u.last_name,
    u.password_hash,
    u.email,
    u.phone,
    u.prefecture_id,
    p.name AS prefecture_name,
    u.city,
    u.street,
    u.building,
    u.postal_code,
    u.deleted_at
FROM users u
JOIN prefectures p ON u.prefecture_id = p.id
WHERE u.id = $1
`

type GetUserDomainByIDRow struct {
	ID             uuid.UUID
	FirstName      string
	LastName       string
	PasswordHash   string
	Email          string
	Phone          string
	PrefectureID   uuid.UUID
	PrefectureName string
	City           string
	Street         string
	Building       sql.NullString
	PostalCode     string
	DeletedAt      sql.NullTime
}

func (q *Queries) GetUserDomainByID(ctx context.Context, userIDParam uuid.NullUUID) (GetUserDomainByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDomainByID, userIDParam)
	var i GetUserDomainByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.PrefectureID,
		&i.PrefectureName,
		&i.City,
		&i.Street,
		&i.Building,
		&i.PostalCode,
		&i.DeletedAt,
	)
	return i, err
}
