// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_command_service.go
//
// Generated by this command:
//
//	mockgen -source=purchase_command_service.go -destination=mock/mock_purchase_command_service.go.gen.go -package=mock_purchase
//

// Package mock_purchase is a generated GoMock package.
package mock_purchase

import (
	context "context"
	purchase "go-boilerplate/internal/domain/purchase"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandService is a mock of CommandService interface.
type MockCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockCommandServiceMockRecorder
	isgomock struct{}
}

// MockCommandServiceMockRecorder is the mock recorder for MockCommandService.
type MockCommandServiceMockRecorder struct {
	mock *MockCommandService
}

// NewMockCommandService creates a new mock instance.
func NewMockCommandService(ctrl *gomock.Controller) *MockCommandService {
	mock := &MockCommandService{ctrl: ctrl}
	mock.recorder = &MockCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandService) EXPECT() *MockCommandServiceMockRecorder {
	return m.recorder
}

// CancelPurchase mocks base method.
func (m *MockCommandService) CancelPurchase(ctx context.Context, p *purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPurchase", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPurchase indicates an expected call of CancelPurchase.
func (mr *MockCommandServiceMockRecorder) CancelPurchase(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPurchase", reflect.TypeOf((*MockCommandService)(nil).CancelPurchase), ctx, p)
}

// CreatePurchase mocks base method.
func (m *MockCommandService) CreatePurchase(ctx context.Context, p *purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockCommandServiceMockRecorder) CreatePurchase(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockCommandService)(nil).CreatePurchase), ctx, p)
}

// LockProducts mocks base method.
func (m *MockCommandService) LockProducts(ctx context.Context, productIDs []uuid.UUID) ([]purchase.LockedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockProducts", ctx, productIDs)
	ret0, _ := ret[0].([]purchase.LockedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockProducts indicates an expected call of LockProducts.
func (mr *MockCommandServiceMockRecorder) LockProducts(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockProducts", reflect.TypeOf((*MockCommandService)(nil).LockProducts), ctx, productIDs)
}

// LockPurchase mocks base method.
func (m *MockCommandService) LockPurchase(ctx context.Context, id uuid.UUID) (*purchase.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockPurchase", ctx, id)
	ret0, _ := ret[0].(*purchase.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockPurchase indicates an expected call of LockPurchase.
func (mr *MockCommandServiceMockRecorder) LockPurchase(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockPurchase", reflect.TypeOf((*MockCommandService)(nil).LockPurchase), ctx, id)
}
