// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_repository.go
//
// Generated by this command:
//
//	mockgen -source=purchase_repository.go -destination=mock/mock_purchase_repository.go.gen.go -package=mock_purchase
//

// Package mock_purchase is a generated GoMock package.
package mock_purchase

import (
	context "context"
	purchase "go-boilerplate/internal/domain/purchase"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*purchase.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*purchase.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindDetailByID mocks base method.
func (m *MockRepository) FindDetailByID(ctx context.Context, id uuid.UUID) (*purchase.Detail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDetailByID", ctx, id)
	ret0, _ := ret[0].(*purchase.Detail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDetailByID indicates an expected call of FindDetailByID.
func (mr *MockRepositoryMockRecorder) FindDetailByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDetailByID", reflect.TypeOf((*MockRepository)(nil).FindDetailByID), ctx, id)
}

// FindShippable mocks base method.
func (m *MockRepository) FindShippable(ctx context.Context, limit int32) (purchase.Purchases, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShippable", ctx, limit)
	ret0, _ := ret[0].(purchase.Purchases)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShippable indicates an expected call of FindShippable.
func (mr *MockRepositoryMockRecorder) FindShippable(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShippable", reflect.TypeOf((*MockRepository)(nil).FindShippable), ctx, limit)
}

// FindStatusesByUserID mocks base method.
func (m *MockRepository) FindStatusesByUserID(ctx context.Context, userID uuid.UUID) ([]purchase.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStatusesByUserID", ctx, userID)
	ret0, _ := ret[0].([]purchase.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStatusesByUserID indicates an expected call of FindStatusesByUserID.
func (mr *MockRepositoryMockRecorder) FindStatusesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStatusesByUserID", reflect.TypeOf((*MockRepository)(nil).FindStatusesByUserID), ctx, userID)
}

// FindUserIDsWithPurchases mocks base method.
func (m *MockRepository) FindUserIDsWithPurchases(ctx context.Context, userIDs []uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserIDsWithPurchases", ctx, userIDs)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserIDsWithPurchases indicates an expected call of FindUserIDsWithPurchases.
func (mr *MockRepositoryMockRecorder) FindUserIDsWithPurchases(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserIDsWithPurchases", reflect.TypeOf((*MockRepository)(nil).FindUserIDsWithPurchases), ctx, userIDs)
}

// LockByCode mocks base method.
func (m *MockRepository) LockByCode(ctx context.Context, code string) (*purchase.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByCode", ctx, code)
	ret0, _ := ret[0].(*purchase.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByCode indicates an expected call of LockByCode.
func (mr *MockRepositoryMockRecorder) LockByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByCode", reflect.TypeOf((*MockRepository)(nil).LockByCode), ctx, code)
}

// UpdateDelivered mocks base method.
func (m *MockRepository) UpdateDelivered(ctx context.Context, p *purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDelivered", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDelivered indicates an expected call of UpdateDelivered.
func (mr *MockRepositoryMockRecorder) UpdateDelivered(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDelivered", reflect.TypeOf((*MockRepository)(nil).UpdateDelivered), ctx, p)
}

// UpdatePaid mocks base method.
func (m *MockRepository) UpdatePaid(ctx context.Context, p *purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaid", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaid indicates an expected call of UpdatePaid.
func (mr *MockRepositoryMockRecorder) UpdatePaid(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaid", reflect.TypeOf((*MockRepository)(nil).UpdatePaid), ctx, p)
}

// UpdateShipped mocks base method.
func (m *MockRepository) UpdateShipped(ctx context.Context, p *purchase.Purchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShipped", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShipped indicates an expected call of UpdateShipped.
func (mr *MockRepositoryMockRecorder) UpdateShipped(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShipped", reflect.TypeOf((*MockRepository)(nil).UpdateShipped), ctx, p)
}
