// Code generated by MockGen. DO NOT EDIT.
// Source: product_ranking_query_service.go
//
// Generated by this command:
//
//	mockgen -source=product_ranking_query_service.go -destination=mock/mock_product_ranking_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/product/ranking/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductRankingQueryService is a mock of ProductRankingQueryService interface.
type MockProductRankingQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockProductRankingQueryServiceMockRecorder
	isgomock struct{}
}

// MockProductRankingQueryServiceMockRecorder is the mock recorder for MockProductRankingQueryService.
type MockProductRankingQueryServiceMockRecorder struct {
	mock *MockProductRankingQueryService
}

// NewMockProductRankingQueryService creates a new mock instance.
func NewMockProductRankingQueryService(ctrl *gomock.Controller) *MockProductRankingQueryService {
	mock := &MockProductRankingQueryService{ctrl: ctrl}
	mock.recorder = &MockProductRankingQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRankingQueryService) EXPECT() *MockProductRankingQueryServiceMockRecorder {
	return m.recorder
}

// ListAmountRanking mocks base method.
func (m *MockProductRankingQueryService) ListAmountRanking(ctx context.Context, params query.RankingQueryParams) ([]query.AmountRankingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAmountRanking", ctx, params)
	ret0, _ := ret[0].([]query.AmountRankingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAmountRanking indicates an expected call of ListAmountRanking.
func (mr *MockProductRankingQueryServiceMockRecorder) ListAmountRanking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAmountRanking", reflect.TypeOf((*MockProductRankingQueryService)(nil).ListAmountRanking), ctx, params)
}

// ListQuantityRanking mocks base method.
func (m *MockProductRankingQueryService) ListQuantityRanking(ctx context.Context, params query.RankingQueryParams) ([]query.QuantityRankingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuantityRanking", ctx, params)
	ret0, _ := ret[0].([]query.QuantityRankingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuantityRanking indicates an expected call of ListQuantityRanking.
func (mr *MockProductRankingQueryServiceMockRecorder) ListQuantityRanking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuantityRanking", reflect.TypeOf((*MockProductRankingQueryService)(nil).ListQuantityRanking), ctx, params)
}
