// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_summary_query_service.go
//
// Generated by this command:
//
//	mockgen -source=purchase_summary_query_service.go -destination=mock/mock_purchase_summary_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/purchase/query"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseSummaryQueryService is a mock of PurchaseSummaryQueryService interface.
type MockPurchaseSummaryQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseSummaryQueryServiceMockRecorder
	isgomock struct{}
}

// MockPurchaseSummaryQueryServiceMockRecorder is the mock recorder for MockPurchaseSummaryQueryService.
type MockPurchaseSummaryQueryServiceMockRecorder struct {
	mock *MockPurchaseSummaryQueryService
}

// NewMockPurchaseSummaryQueryService creates a new mock instance.
func NewMockPurchaseSummaryQueryService(ctrl *gomock.Controller) *MockPurchaseSummaryQueryService {
	mock := &MockPurchaseSummaryQueryService{ctrl: ctrl}
	mock.recorder = &MockPurchaseSummaryQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseSummaryQueryService) EXPECT() *MockPurchaseSummaryQueryServiceMockRecorder {
	return m.recorder
}

// SummarizeByUserID mocks base method.
func (m *MockPurchaseSummaryQueryService) SummarizeByUserID(ctx context.Context, userID uuid.UUID) ([]query.PurchaseStatusSummaryReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizeByUserID", ctx, userID)
	ret0, _ := ret[0].([]query.PurchaseStatusSummaryReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummarizeByUserID indicates an expected call of SummarizeByUserID.
func (mr *MockPurchaseSummaryQueryServiceMockRecorder) SummarizeByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizeByUserID", reflect.TypeOf((*MockPurchaseSummaryQueryService)(nil).SummarizeByUserID), ctx, userID)
}
