// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_feed_query_service.go
//
// Generated by this command:
//
//	mockgen -source=purchase_feed_query_service.go -destination=mock/mock_purchase_feed_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/purchase/query"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseFeedQueryService is a mock of PurchaseFeedQueryService interface.
type MockPurchaseFeedQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseFeedQueryServiceMockRecorder
	isgomock struct{}
}

// MockPurchaseFeedQueryServiceMockRecorder is the mock recorder for MockPurchaseFeedQueryService.
type MockPurchaseFeedQueryServiceMockRecorder struct {
	mock *MockPurchaseFeedQueryService
}

// NewMockPurchaseFeedQueryService creates a new mock instance.
func NewMockPurchaseFeedQueryService(ctrl *gomock.Controller) *MockPurchaseFeedQueryService {
	mock := &MockPurchaseFeedQueryService{ctrl: ctrl}
	mock.recorder = &MockPurchaseFeedQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseFeedQueryService) EXPECT() *MockPurchaseFeedQueryServiceMockRecorder {
	return m.recorder
}

// FindFeedByUserID mocks base method.
func (m *MockPurchaseFeedQueryService) FindFeedByUserID(ctx context.Context, userID uuid.UUID, params query.ListFeedParams) ([]query.PurchaseFeedReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFeedByUserID", ctx, userID, params)
	ret0, _ := ret[0].([]query.PurchaseFeedReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFeedByUserID indicates an expected call of FindFeedByUserID.
func (mr *MockPurchaseFeedQueryServiceMockRecorder) FindFeedByUserID(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFeedByUserID", reflect.TypeOf((*MockPurchaseFeedQueryService)(nil).FindFeedByUserID), ctx, userID, params)
}
