// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_detail_query_service.go
//
// Generated by this command:
//
//	mockgen -source=purchase_detail_query_service.go -destination=mock/mock_purchase_detail_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/purchase/query"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseDetailQueryService is a mock of PurchaseDetailQueryService interface.
type MockPurchaseDetailQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseDetailQueryServiceMockRecorder
	isgomock struct{}
}

// MockPurchaseDetailQueryServiceMockRecorder is the mock recorder for MockPurchaseDetailQueryService.
type MockPurchaseDetailQueryServiceMockRecorder struct {
	mock *MockPurchaseDetailQueryService
}

// NewMockPurchaseDetailQueryService creates a new mock instance.
func NewMockPurchaseDetailQueryService(ctrl *gomock.Controller) *MockPurchaseDetailQueryService {
	mock := &MockPurchaseDetailQueryService{ctrl: ctrl}
	mock.recorder = &MockPurchaseDetailQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseDetailQueryService) EXPECT() *MockPurchaseDetailQueryServiceMockRecorder {
	return m.recorder
}

// FindDetailByUserAndID mocks base method.
func (m *MockPurchaseDetailQueryService) FindDetailByUserAndID(ctx context.Context, userID, purchaseID uuid.UUID) (*query.PurchaseDetailReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDetailByUserAndID", ctx, userID, purchaseID)
	ret0, _ := ret[0].(*query.PurchaseDetailReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDetailByUserAndID indicates an expected call of FindDetailByUserAndID.
func (mr *MockPurchaseDetailQueryServiceMockRecorder) FindDetailByUserAndID(ctx, userID, purchaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDetailByUserAndID", reflect.TypeOf((*MockPurchaseDetailQueryService)(nil).FindDetailByUserAndID), ctx, userID, purchaseID)
}
