// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard_usecase.go
//
// Generated by this command:
//
//	mockgen -source=dashboard_usecase.go -destination=mock/mock_dashboard_usecase.go.gen.go -package=mock_dashboard
//

// Package mock_dashboard is a generated GoMock package.
package mock_dashboard

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	dashboard "go-boilerplate/internal/usecase/dashboard"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetDashboardSummary mocks base method.
func (m *MockUsecase) GetDashboardSummary(ctx context.Context, authn *auth.Authn, params dashboard.GetSummaryParams) (dashboard.SummaryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardSummary", ctx, authn, params)
	ret0, _ := ret[0].(dashboard.SummaryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardSummary indicates an expected call of GetDashboardSummary.
func (mr *MockUsecaseMockRecorder) GetDashboardSummary(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardSummary", reflect.TypeOf((*MockUsecase)(nil).GetDashboardSummary), ctx, authn, params)
}
