// Code generated by MockGen. DO NOT EDIT.
// Source: lock_repository.go
//
// Generated by this command:
//
//	mockgen -source=lock_repository.go -destination=mock/mock_lock_repository.go.gen.go -package=mock_user
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	user "go-boilerplate/internal/domain/user"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLockRepository is a mock of LockRepository interface.
type MockLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLockRepositoryMockRecorder
	isgomock struct{}
}

// MockLockRepositoryMockRecorder is the mock recorder for MockLockRepository.
type MockLockRepositoryMockRecorder struct {
	mock *MockLockRepository
}

// NewMockLockRepository creates a new mock instance.
func NewMockLockRepository(ctrl *gomock.Controller) *MockLockRepository {
	mock := &MockLockRepository{ctrl: ctrl}
	mock.recorder = &MockLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockRepository) EXPECT() *MockLockRepositoryMockRecorder {
	return m.recorder
}

// LockActiveShareByID mocks base method.
func (m *MockLockRepository) LockActiveShareByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockActiveShareByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockActiveShareByID indicates an expected call of LockActiveShareByID.
func (mr *MockLockRepositoryMockRecorder) LockActiveShareByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockActiveShareByID", reflect.TypeOf((*MockLockRepository)(nil).LockActiveShareByID), ctx, id)
}

// LockByID mocks base method.
func (m *MockLockRepository) LockByID(ctx context.Context, id uuid.UUID) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByID", ctx, id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByID indicates an expected call of LockByID.
func (mr *MockLockRepositoryMockRecorder) LockByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByID", reflect.TypeOf((*MockLockRepository)(nil).LockByID), ctx, id)
}
