// Code generated by MockGen. DO NOT EDIT.
// Source: health_check_usecase.go
//
// Generated by this command:
//
//	mockgen -source=health_check_usecase.go -destination=mock/mock_health_check_usecase.go.gen.go -package=mock_healthcheck
//

// Package mock_healthcheck is a generated GoMock package.
package mock_healthcheck

import (
	context "context"
	healthcheck "go-boilerplate/internal/usecase/healthcheck"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockUsecase) CheckHealth(ctx context.Context) (*healthcheck.DTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(*healthcheck.DTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockUsecaseMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockUsecase)(nil).CheckHealth), ctx)
}
