// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/mock_interface.go -package=mock_xerrors
//

// Package mock_xerrors is a generated GoMock package.
package mock_xerrors

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockErrors is a mock of Errors interface.
type MockErrors struct {
	ctrl     *gomock.Controller
	recorder *MockErrorsMockRecorder
	isgomock struct{}
}

// MockErrorsMockRecorder is the mock recorder for MockErrors.
type MockErrorsMockRecorder struct {
	mock *MockErrors
}

// NewMockErrors creates a new mock instance.
func NewMockErrors(ctrl *gomock.Controller) *MockErrors {
	mock := &MockErrors{ctrl: ctrl}
	mock.recorder = &MockErrorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrors) EXPECT() *MockErrorsMockRecorder {
	return m.recorder
}

// As mocks base method.
func (m *MockErrors) As(err error, target any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "As", err, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// As indicates an expected call of As.
func (mr *MockErrorsMockRecorder) As(err, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "As", reflect.TypeOf((*MockErrors)(nil).As), err, target)
}

// Is mocks base method.
func (m *MockErrors) Is(err, target error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Is", err, target)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Is indicates an expected call of Is.
func (mr *MockErrorsMockRecorder) Is(err, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Is", reflect.TypeOf((*MockErrors)(nil).Is), err, target)
}

// New mocks base method.
func (m *MockErrors) New(msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockErrorsMockRecorder) New(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockErrors)(nil).New), msg)
}

// StackTrace mocks base method.
func (m *MockErrors) StackTrace(err error) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StackTrace", err)
	ret0, _ := ret[0].(string)
	return ret0
}

// StackTrace indicates an expected call of StackTrace.
func (mr *MockErrorsMockRecorder) StackTrace(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StackTrace", reflect.TypeOf((*MockErrors)(nil).StackTrace), err)
}

// Wrap mocks base method.
func (m *MockErrors) Wrap(err error, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wrap", err, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wrap indicates an expected call of Wrap.
func (mr *MockErrorsMockRecorder) Wrap(err, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wrap", reflect.TypeOf((*MockErrors)(nil).Wrap), err, msg)
}
