// Code generated by MockGen. DO NOT EDIT.
// Source: user_usecase_query_service.go
//
// Generated by this command:
//
//	mockgen -source=user_usecase_query_service.go -destination=mock/mock_user_usecase_query_service.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	user "boilerplate-go/internal/domain/user"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserQueryService is a mock of UserQueryService interface.
type MockUserQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueryServiceMockRecorder
	isgomock struct{}
}

// MockUserQueryServiceMockRecorder is the mock recorder for MockUserQueryService.
type MockUserQueryServiceMockRecorder struct {
	mock *MockUserQueryService
}

// NewMockUserQueryService creates a new mock instance.
func NewMockUserQueryService(ctrl *gomock.Controller) *MockUserQueryService {
	mock := &MockUserQueryService{ctrl: ctrl}
	mock.recorder = &MockUserQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueryService) EXPECT() *MockUserQueryServiceMockRecorder {
	return m.recorder
}

// FindByKeyword mocks base method.
func (m *MockUserQueryService) FindByKeyword(ctx context.Context, keywords []string, active *bool, limit, offset int32) (user.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keywords, active, limit, offset)
	ret0, _ := ret[0].(user.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockUserQueryServiceMockRecorder) FindByKeyword(ctx, keywords, active, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockUserQueryService)(nil).FindByKeyword), ctx, keywords, active, limit, offset)
}
