// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock/mock_store.go.gen.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	outbox "go-boilerplate/internal/usecase/boundary/outbox"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClaimPending mocks base method.
func (m *MockStore) ClaimPending(ctx context.Context, limit int32) ([]outbox.PendingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPending", ctx, limit)
	ret0, _ := ret[0].([]outbox.PendingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPending indicates an expected call of ClaimPending.
func (mr *MockStoreMockRecorder) ClaimPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPending", reflect.TypeOf((*MockStore)(nil).ClaimPending), ctx, limit)
}

// DeletePublished mocks base method.
func (m *MockStore) DeletePublished(ctx context.Context, cutoff time.Time, limit int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePublished", ctx, cutoff, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePublished indicates an expected call of DeletePublished.
func (mr *MockStoreMockRecorder) DeletePublished(ctx, cutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublished", reflect.TypeOf((*MockStore)(nil).DeletePublished), ctx, cutoff, limit)
}

// Insert mocks base method.
func (m *MockStore) Insert(ctx context.Context, p outbox.EmitParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockStoreMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStore)(nil).Insert), ctx, p)
}

// MarkDead mocks base method.
func (m *MockStore) MarkDead(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDead", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDead indicates an expected call of MarkDead.
func (mr *MockStoreMockRecorder) MarkDead(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDead", reflect.TypeOf((*MockStore)(nil).MarkDead), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockStore) MarkFailed(ctx context.Context, id int64, lastErr string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, lastErr)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockStoreMockRecorder) MarkFailed(ctx, id, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockStore)(nil).MarkFailed), ctx, id, lastErr)
}

// MarkPublished mocks base method.
func (m *MockStore) MarkPublished(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockStoreMockRecorder) MarkPublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockStore)(nil).MarkPublished), ctx, id)
}

// OldestPendingCreatedAt mocks base method.
func (m *MockStore) OldestPendingCreatedAt(ctx context.Context) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestPendingCreatedAt", ctx)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OldestPendingCreatedAt indicates an expected call of OldestPendingCreatedAt.
func (mr *MockStoreMockRecorder) OldestPendingCreatedAt(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestPendingCreatedAt", reflect.TypeOf((*MockStore)(nil).OldestPendingCreatedAt), ctx)
}

// ReplayDead mocks base method.
func (m *MockStore) ReplayDead(ctx context.Context, messageID *uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDead", ctx, messageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayDead indicates an expected call of ReplayDead.
func (mr *MockStoreMockRecorder) ReplayDead(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDead", reflect.TypeOf((*MockStore)(nil).ReplayDead), ctx, messageID)
}
