// Code generated by MockGen. DO NOT EDIT.
// Source: bcrypt_hasher.go
//
// Generated by this command:
//
//	mockgen -source=bcrypt_hasher.go -destination=mock/mock_bcrypt_hasher.go -package=mock_security
//

// Package mock_security is a generated GoMock package.
package mock_security

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBcrypter is a mock of Bcrypter interface.
type MockBcrypter struct {
	ctrl     *gomock.Controller
	recorder *MockBcrypterMockRecorder
	isgomock struct{}
}

// MockBcrypterMockRecorder is the mock recorder for MockBcrypter.
type MockBcrypterMockRecorder struct {
	mock *MockBcrypter
}

// NewMockBcrypter creates a new mock instance.
func NewMockBcrypter(ctrl *gomock.Controller) *MockBcrypter {
	mock := &MockBcrypter{ctrl: ctrl}
	mock.recorder = &MockBcrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBcrypter) EXPECT() *MockBcrypterMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockBcrypter) Compare(hash, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockBcrypterMockRecorder) Compare(hash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockBcrypter)(nil).Compare), hash, password)
}

// Hash mocks base method.
func (m *MockBcrypter) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockBcrypterMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockBcrypter)(nil).Hash), password)
}
