// Code generated by MockGen. DO NOT EDIT.
// Source: checkout_usecase.go
//
// Generated by this command:
//
//	mockgen -source=checkout_usecase.go -destination=mock/mock_checkout_usecase.go.gen.go -package=mock_checkout
//

// Package mock_checkout is a generated GoMock package.
package mock_checkout

import (
	context "context"
	checkout "go-boilerplate/internal/usecase/checkout"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreatePurchase mocks base method.
func (m *MockUsecase) CreatePurchase(ctx context.Context, params checkout.CreatePurchaseParams) (checkout.PurchaseView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", ctx, params)
	ret0, _ := ret[0].(checkout.PurchaseView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockUsecaseMockRecorder) CreatePurchase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockUsecase)(nil).CreatePurchase), ctx, params)
}
