get:
  operationId: GetOpenidConfiguration
  tags:
    - discovery
  summary: OIDC Discovery 文書の取得
  security: []
  responses:
    '200':
      description: OIDC Discovery 文書
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/OidcConfiguration.yaml'
