// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source=state.go -destination=mock/mock_state.go.gen.go -package=mock_worker
//

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockState) Set(name string, args []string, done chan error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", name, args, done)
}

// Set indicates an expected call of Set.
func (mr *MockStateMockRecorder) Set(name, args, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockState)(nil).Set), name, args, done)
}

// Snapshot mocks base method.
func (m *MockState) Snapshot() (string, []string, chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(chan error)
	return ret0, ret1, ret2
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStateMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockState)(nil).Snapshot))
}
