// Code generated by MockGen. DO NOT EDIT.
// Source: queue_stats.go
//
// Generated by this command:
//
//	mockgen -source=queue_stats.go -destination=mock/mock_queue_stats.go.gen.go -package=mock_worker
//

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	worker "go-boilerplate/internal/usecase/boundary/worker"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueueStatsProvider is a mock of QueueStatsProvider interface.
type MockQueueStatsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockQueueStatsProviderMockRecorder
	isgomock struct{}
}

// MockQueueStatsProviderMockRecorder is the mock recorder for MockQueueStatsProvider.
type MockQueueStatsProviderMockRecorder struct {
	mock *MockQueueStatsProvider
}

// NewMockQueueStatsProvider creates a new mock instance.
func NewMockQueueStatsProvider(ctrl *gomock.Controller) *MockQueueStatsProvider {
	mock := &MockQueueStatsProvider{ctrl: ctrl}
	mock.recorder = &MockQueueStatsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueStatsProvider) EXPECT() *MockQueueStatsProviderMockRecorder {
	return m.recorder
}

// QueueStats mocks base method.
func (m *MockQueueStatsProvider) QueueStats(ctx context.Context) (worker.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueStats", ctx)
	ret0, _ := ret[0].(worker.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueStats indicates an expected call of QueueStats.
func (mr *MockQueueStatsProviderMockRecorder) QueueStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueStats", reflect.TypeOf((*MockQueueStatsProvider)(nil).QueueStats), ctx)
}
