// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go
//
// Generated by this command:
//
//	mockgen -source=consumer.go -destination=mock/mock_consumer.gen.go -package=mock_worker
//

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	worker "go-boilerplate/internal/usecase/boundary/worker"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConsumer is a mock of Consumer interface.
type MockConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMockRecorder
	isgomock struct{}
}

// MockConsumerMockRecorder is the mock recorder for MockConsumer.
type MockConsumerMockRecorder struct {
	mock *MockConsumer
}

// NewMockConsumer creates a new mock instance.
func NewMockConsumer(ctrl *gomock.Controller) *MockConsumer {
	mock := &MockConsumer{ctrl: ctrl}
	mock.recorder = &MockConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumer) EXPECT() *MockConsumerMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m_2 *MockConsumer) Ack(ctx context.Context, m worker.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Ack", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockConsumerMockRecorder) Ack(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockConsumer)(nil).Ack), ctx, m)
}

// Extend mocks base method.
func (m_2 *MockConsumer) Extend(ctx context.Context, m worker.Message, d time.Duration) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Extend", ctx, m, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extend indicates an expected call of Extend.
func (mr *MockConsumerMockRecorder) Extend(ctx, m, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extend", reflect.TypeOf((*MockConsumer)(nil).Extend), ctx, m, d)
}

// Nack mocks base method.
func (m_2 *MockConsumer) Nack(ctx context.Context, m worker.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Nack", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockConsumerMockRecorder) Nack(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockConsumer)(nil).Nack), ctx, m)
}

// Receive mocks base method.
func (m *MockConsumer) Receive(ctx context.Context, max int) ([]worker.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, max)
	ret0, _ := ret[0].([]worker.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockConsumerMockRecorder) Receive(ctx, max any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockConsumer)(nil).Receive), ctx, max)
}
