// Code generated by MockGen. DO NOT EDIT.
// Source: failure.go
//
// Generated by this command:
//
//	mockgen -source=failure.go -destination=mock/mock_failure.gen.go -package=mock_worker
//

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	worker "go-boilerplate/internal/usecase/boundary/worker"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFailureHandler is a mock of FailureHandler interface.
type MockFailureHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFailureHandlerMockRecorder
	isgomock struct{}
}

// MockFailureHandlerMockRecorder is the mock recorder for MockFailureHandler.
type MockFailureHandlerMockRecorder struct {
	mock *MockFailureHandler
}

// NewMockFailureHandler creates a new mock instance.
func NewMockFailureHandler(ctrl *gomock.Controller) *MockFailureHandler {
	mock := &MockFailureHandler{ctrl: ctrl}
	mock.recorder = &MockFailureHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureHandler) EXPECT() *MockFailureHandlerMockRecorder {
	return m.recorder
}

// Fail mocks base method.
func (m_2 *MockFailureHandler) Fail(ctx context.Context, m worker.Message, cause error) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Fail", ctx, m, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fail indicates an expected call of Fail.
func (mr *MockFailureHandlerMockRecorder) Fail(ctx, m, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockFailureHandler)(nil).Fail), ctx, m, cause)
}
