// Code generated by MockGen. DO NOT EDIT.
// Source: user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=user_usecase.go -destination=mock/mock_user_usecase.gen.go -package=mock_user
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	paging "go-boilerplate/internal/usecase/tools/paging"
	user "go-boilerplate/internal/usecase/user"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUsecase) ChangePassword(ctx context.Context, id uuid.UUID, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, id, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUsecaseMockRecorder) ChangePassword(ctx, id, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUsecase)(nil).ChangePassword), ctx, id, currentPassword, newPassword)
}

// CountUsers mocks base method.
func (m *MockUsecase) CountUsers(ctx context.Context, active *bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx, active)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUsecaseMockRecorder) CountUsers(ctx, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUsecase)(nil).CountUsers), ctx, active)
}

// CreateUser mocks base method.
func (m *MockUsecase) CreateUser(ctx context.Context, dto *user.CreateParamsDTO) (user.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, dto)
	ret0, _ := ret[0].(user.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsecaseMockRecorder) CreateUser(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsecase)(nil).CreateUser), ctx, dto)
}

// DeleteUser mocks base method.
func (m *MockUsecase) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsecaseMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsecase)(nil).DeleteUser), ctx, id)
}

// GetUser mocks base method.
func (m *MockUsecase) GetUser(ctx context.Context, id uuid.UUID) (user.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(user.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsecaseMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsecase)(nil).GetUser), ctx, id)
}

// ListUsers mocks base method.
func (m *MockUsecase) ListUsers(ctx context.Context, active *bool, page *paging.Paging) ([]user.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, active, page)
	ret0, _ := ret[0].([]user.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUsecaseMockRecorder) ListUsers(ctx, active, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUsecase)(nil).ListUsers), ctx, active, page)
}

// ListUsersFeed mocks base method.
func (m *MockUsecase) ListUsersFeed(ctx context.Context, cursor *paging.Cursor) (*user.UserFeedView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersFeed", ctx, cursor)
	ret0, _ := ret[0].(*user.UserFeedView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersFeed indicates an expected call of ListUsersFeed.
func (mr *MockUsecaseMockRecorder) ListUsersFeed(ctx, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersFeed", reflect.TypeOf((*MockUsecase)(nil).ListUsersFeed), ctx, cursor)
}

// ListUsersWithTotal mocks base method.
func (m *MockUsecase) ListUsersWithTotal(ctx context.Context, active *bool, page *paging.Paging) (*user.UserListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersWithTotal", ctx, active, page)
	ret0, _ := ret[0].(*user.UserListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersWithTotal indicates an expected call of ListUsersWithTotal.
func (mr *MockUsecaseMockRecorder) ListUsersWithTotal(ctx, active, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersWithTotal", reflect.TypeOf((*MockUsecase)(nil).ListUsersWithTotal), ctx, active, page)
}

// UpdateUser mocks base method.
func (m *MockUsecase) UpdateUser(ctx context.Context, id uuid.UUID, dto *user.UpdateProfileParams) (user.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, dto)
	ret0, _ := ret[0].(user.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsecaseMockRecorder) UpdateUser(ctx, id, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsecase)(nil).UpdateUser), ctx, id, dto)
}

// UpdateUserPartially mocks base method.
func (m *MockUsecase) UpdateUserPartially(ctx context.Context, id uuid.UUID, dto *user.PatchParamsDTO) (user.UserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPartially", ctx, id, dto)
	ret0, _ := ret[0].(user.UserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPartially indicates an expected call of UpdateUserPartially.
func (mr *MockUsecaseMockRecorder) UpdateUserPartially(ctx, id, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPartially", reflect.TypeOf((*MockUsecase)(nil).UpdateUserPartially), ctx, id, dto)
}
