// Code generated by MockGen. DO NOT EDIT.
// Source: withdrawal_archive_usecase.go
//
// Generated by this command:
//
//	mockgen -source=withdrawal_archive_usecase.go -destination=mock/mock_withdrawal_archive_usecase.go.gen.go -package=mock_user
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	user "go-boilerplate/internal/usecase/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArchiveUsecase is a mock of ArchiveUsecase interface.
type MockArchiveUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveUsecaseMockRecorder
	isgomock struct{}
}

// MockArchiveUsecaseMockRecorder is the mock recorder for MockArchiveUsecase.
type MockArchiveUsecaseMockRecorder struct {
	mock *MockArchiveUsecase
}

// NewMockArchiveUsecase creates a new mock instance.
func NewMockArchiveUsecase(ctrl *gomock.Controller) *MockArchiveUsecase {
	mock := &MockArchiveUsecase{ctrl: ctrl}
	mock.recorder = &MockArchiveUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveUsecase) EXPECT() *MockArchiveUsecaseMockRecorder {
	return m.recorder
}

// ArchiveWithdrawal mocks base method.
func (m *MockArchiveUsecase) ArchiveWithdrawal(ctx context.Context, params user.ArchiveWithdrawalParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveWithdrawal", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveWithdrawal indicates an expected call of ArchiveWithdrawal.
func (mr *MockArchiveUsecaseMockRecorder) ArchiveWithdrawal(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveWithdrawal", reflect.TypeOf((*MockArchiveUsecase)(nil).ArchiveWithdrawal), ctx, params)
}
