// Code generated by MockGen. DO NOT EDIT.
// Source: user_usecase.go
//
// Generated by this command:
//
//	mockgen -source=user_usecase.go -destination=mock/mock_user_usecase.go -package=mock_user
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	paging "boilerplate-go/internal/usecase/support/paging"
	user "boilerplate-go/internal/usecase/user"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUsecase) CountUsers(ctx context.Context, active *bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx, active)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUsecaseMockRecorder) CountUsers(ctx, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUsecase)(nil).CountUsers), ctx, active)
}

// CreateUser mocks base method.
func (m *MockUsecase) CreateUser(ctx context.Context, dto *user.CreateParamsDTO) (user.MutableFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, dto)
	ret0, _ := ret[0].(user.MutableFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsecaseMockRecorder) CreateUser(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsecase)(nil).CreateUser), ctx, dto)
}

// ListUsersByKeyword mocks base method.
func (m *MockUsecase) ListUsersByKeyword(ctx context.Context, params *user.GetParamsDTO, page *paging.Paging) ([]user.MutableFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByKeyword", ctx, params, page)
	ret0, _ := ret[0].([]user.MutableFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByKeyword indicates an expected call of ListUsersByKeyword.
func (mr *MockUsecaseMockRecorder) ListUsersByKeyword(ctx, params, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByKeyword", reflect.TypeOf((*MockUsecase)(nil).ListUsersByKeyword), ctx, params, page)
}
