// Code generated by MockGen. DO NOT EDIT.
// Source: user_purge_usecase.go
//
// Generated by this command:
//
//	mockgen -source=user_purge_usecase.go -destination=mock/mock_user_purge_usecase.go.gen.go -package=mock_user
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	user "go-boilerplate/internal/usecase/user"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPurgeUsecase is a mock of PurgeUsecase interface.
type MockPurgeUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPurgeUsecaseMockRecorder
	isgomock struct{}
}

// MockPurgeUsecaseMockRecorder is the mock recorder for MockPurgeUsecase.
type MockPurgeUsecaseMockRecorder struct {
	mock *MockPurgeUsecase
}

// NewMockPurgeUsecase creates a new mock instance.
func NewMockPurgeUsecase(ctrl *gomock.Controller) *MockPurgeUsecase {
	mock := &MockPurgeUsecase{ctrl: ctrl}
	mock.recorder = &MockPurgeUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurgeUsecase) EXPECT() *MockPurgeUsecaseMockRecorder {
	return m.recorder
}

// PurgeDeleted mocks base method.
func (m *MockPurgeUsecase) PurgeDeleted(ctx context.Context, retention time.Duration, batchSize int32, dryRun bool) (user.PurgeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeDeleted", ctx, retention, batchSize, dryRun)
	ret0, _ := ret[0].(user.PurgeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeDeleted indicates an expected call of PurgeDeleted.
func (mr *MockPurgeUsecaseMockRecorder) PurgeDeleted(ctx, retention, batchSize, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeDeleted", reflect.TypeOf((*MockPurgeUsecase)(nil).PurgeDeleted), ctx, retention, batchSize, dryRun)
}
