// Code generated by MockGen. DO NOT EDIT.
// Source: eventlog.go
//
// Generated by this command:
//
//	mockgen -source=eventlog.go -destination=mock/mock_eventlog.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventLogStore is a mock of EventLogStore interface.
type MockEventLogStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventLogStoreMockRecorder
	isgomock struct{}
}

// MockEventLogStoreMockRecorder is the mock recorder for MockEventLogStore.
type MockEventLogStoreMockRecorder struct {
	mock *MockEventLogStore
}

// NewMockEventLogStore creates a new mock instance.
func NewMockEventLogStore(ctrl *gomock.Controller) *MockEventLogStore {
	mock := &MockEventLogStore{ctrl: ctrl}
	mock.recorder = &MockEventLogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLogStore) EXPECT() *MockEventLogStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEventLogStore) Append(ctx context.Context, event realtime.DeliveryEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockEventLogStoreMockRecorder) Append(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEventLogStore)(nil).Append), ctx, event)
}

// AppendedThrough mocks base method.
func (m *MockEventLogStore) AppendedThrough(ctx context.Context, streamID realtime.StreamID) (realtime.Sequence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendedThrough", ctx, streamID)
	ret0, _ := ret[0].(realtime.Sequence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendedThrough indicates an expected call of AppendedThrough.
func (mr *MockEventLogStoreMockRecorder) AppendedThrough(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendedThrough", reflect.TypeOf((*MockEventLogStore)(nil).AppendedThrough), ctx, streamID)
}

// Find mocks base method.
func (m *MockEventLogStore) Find(ctx context.Context, streamID realtime.StreamID, seq realtime.Sequence) (realtime.DeliveryEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, streamID, seq)
	ret0, _ := ret[0].(realtime.DeliveryEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockEventLogStoreMockRecorder) Find(ctx, streamID, seq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockEventLogStore)(nil).Find), ctx, streamID, seq)
}

// Latest mocks base method.
func (m *MockEventLogStore) Latest(ctx context.Context, streamID realtime.StreamID) (realtime.DeliveryEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx, streamID)
	ret0, _ := ret[0].(realtime.DeliveryEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Latest indicates an expected call of Latest.
func (mr *MockEventLogStoreMockRecorder) Latest(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockEventLogStore)(nil).Latest), ctx, streamID)
}

// ReadAfter mocks base method.
func (m *MockEventLogStore) ReadAfter(ctx context.Context, q realtime.ReadAfterQuery) (realtime.ReadAfterResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAfter", ctx, q)
	ret0, _ := ret[0].(realtime.ReadAfterResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAfter indicates an expected call of ReadAfter.
func (mr *MockEventLogStoreMockRecorder) ReadAfter(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAfter", reflect.TypeOf((*MockEventLogStore)(nil).ReadAfter), ctx, q)
}
