// Code generated by MockGen. DO NOT EDIT.
// Source: ticket.go
//
// Generated by this command:
//
//	mockgen -source=ticket.go -destination=mock/mock_ticket.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamTicketStore is a mock of StreamTicketStore interface.
type MockStreamTicketStore struct {
	ctrl     *gomock.Controller
	recorder *MockStreamTicketStoreMockRecorder
	isgomock struct{}
}

// MockStreamTicketStoreMockRecorder is the mock recorder for MockStreamTicketStore.
type MockStreamTicketStoreMockRecorder struct {
	mock *MockStreamTicketStore
}

// NewMockStreamTicketStore creates a new mock instance.
func NewMockStreamTicketStore(ctrl *gomock.Controller) *MockStreamTicketStore {
	mock := &MockStreamTicketStore{ctrl: ctrl}
	mock.recorder = &MockStreamTicketStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamTicketStore) EXPECT() *MockStreamTicketStoreMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStreamTicketStore) Find(ctx context.Context, hash realtime.TicketHash, asOf time.Time) (realtime.StreamTicket, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, hash, asOf)
	ret0, _ := ret[0].(realtime.StreamTicket)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockStreamTicketStoreMockRecorder) Find(ctx, hash, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStreamTicketStore)(nil).Find), ctx, hash, asOf)
}

// Invalidate mocks base method.
func (m *MockStreamTicketStore) Invalidate(ctx context.Context, subject string, destination realtime.StreamID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, subject, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockStreamTicketStoreMockRecorder) Invalidate(ctx, subject, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockStreamTicketStore)(nil).Invalidate), ctx, subject, destination)
}

// Save mocks base method.
func (m *MockStreamTicketStore) Save(ctx context.Context, ticket realtime.StreamTicket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStreamTicketStoreMockRecorder) Save(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStreamTicketStore)(nil).Save), ctx, ticket)
}
