// Code generated by MockGen. DO NOT EDIT.
// Source: sequence.go
//
// Generated by this command:
//
//	mockgen -source=sequence.go -destination=mock/mock_sequence.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSequenceAllocator is a mock of SequenceAllocator interface.
type MockSequenceAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockSequenceAllocatorMockRecorder
	isgomock struct{}
}

// MockSequenceAllocatorMockRecorder is the mock recorder for MockSequenceAllocator.
type MockSequenceAllocatorMockRecorder struct {
	mock *MockSequenceAllocator
}

// NewMockSequenceAllocator creates a new mock instance.
func NewMockSequenceAllocator(ctrl *gomock.Controller) *MockSequenceAllocator {
	mock := &MockSequenceAllocator{ctrl: ctrl}
	mock.recorder = &MockSequenceAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSequenceAllocator) EXPECT() *MockSequenceAllocatorMockRecorder {
	return m.recorder
}

// Allocate mocks base method.
func (m *MockSequenceAllocator) Allocate(ctx context.Context, streamID realtime.StreamID) (realtime.Sequence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allocate", ctx, streamID)
	ret0, _ := ret[0].(realtime.Sequence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allocate indicates an expected call of Allocate.
func (mr *MockSequenceAllocatorMockRecorder) Allocate(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allocate", reflect.TypeOf((*MockSequenceAllocator)(nil).Allocate), ctx, streamID)
}

// Current mocks base method.
func (m *MockSequenceAllocator) Current(ctx context.Context, streamID realtime.StreamID) (realtime.Sequence, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx, streamID)
	ret0, _ := ret[0].(realtime.Sequence)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Current indicates an expected call of Current.
func (mr *MockSequenceAllocatorMockRecorder) Current(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockSequenceAllocator)(nil).Current), ctx, streamID)
}
