// Code generated by MockGen. DO NOT EDIT.
// Source: cleanup.go
//
// Generated by this command:
//
//	mockgen -source=cleanup.go -destination=mock/mock_cleanup.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrphanReclaimer is a mock of OrphanReclaimer interface.
type MockOrphanReclaimer struct {
	ctrl     *gomock.Controller
	recorder *MockOrphanReclaimerMockRecorder
	isgomock struct{}
}

// MockOrphanReclaimerMockRecorder is the mock recorder for MockOrphanReclaimer.
type MockOrphanReclaimerMockRecorder struct {
	mock *MockOrphanReclaimer
}

// NewMockOrphanReclaimer creates a new mock instance.
func NewMockOrphanReclaimer(ctrl *gomock.Controller) *MockOrphanReclaimer {
	mock := &MockOrphanReclaimer{ctrl: ctrl}
	mock.recorder = &MockOrphanReclaimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrphanReclaimer) EXPECT() *MockOrphanReclaimerMockRecorder {
	return m.recorder
}

// Reclaim mocks base method.
func (m *MockOrphanReclaimer) Reclaim(ctx context.Context, id realtime.InstanceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reclaim", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reclaim indicates an expected call of Reclaim.
func (mr *MockOrphanReclaimerMockRecorder) Reclaim(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reclaim", reflect.TypeOf((*MockOrphanReclaimer)(nil).Reclaim), ctx, id)
}
