// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go
//
// Generated by this command:
//
//	mockgen -source=secret.go -destination=mock/mock_secret.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecretGenerator is a mock of SecretGenerator interface.
type MockSecretGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSecretGeneratorMockRecorder
	isgomock struct{}
}

// MockSecretGeneratorMockRecorder is the mock recorder for MockSecretGenerator.
type MockSecretGeneratorMockRecorder struct {
	mock *MockSecretGenerator
}

// NewMockSecretGenerator creates a new mock instance.
func NewMockSecretGenerator(ctrl *gomock.Controller) *MockSecretGenerator {
	mock := &MockSecretGenerator{ctrl: ctrl}
	mock.recorder = &MockSecretGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretGenerator) EXPECT() *MockSecretGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSecretGenerator) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockSecretGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSecretGenerator)(nil).Generate))
}
