// Code generated by MockGen. DO NOT EDIT.
// Source: lease.go
//
// Generated by this command:
//
//	mockgen -source=lease.go -destination=mock/mock_lease.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockInstanceLeaseStore is a mock of InstanceLeaseStore interface.
type MockInstanceLeaseStore struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceLeaseStoreMockRecorder
	isgomock struct{}
}

// MockInstanceLeaseStoreMockRecorder is the mock recorder for MockInstanceLeaseStore.
type MockInstanceLeaseStoreMockRecorder struct {
	mock *MockInstanceLeaseStore
}

// NewMockInstanceLeaseStore creates a new mock instance.
func NewMockInstanceLeaseStore(ctrl *gomock.Controller) *MockInstanceLeaseStore {
	mock := &MockInstanceLeaseStore{ctrl: ctrl}
	mock.recorder = &MockInstanceLeaseStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceLeaseStore) EXPECT() *MockInstanceLeaseStoreMockRecorder {
	return m.recorder
}

// AcquireCleanup mocks base method.
func (m *MockInstanceLeaseStore) AcquireCleanup(ctx context.Context, claim realtime.CleanupClaim) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireCleanup", ctx, claim)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireCleanup indicates an expected call of AcquireCleanup.
func (mr *MockInstanceLeaseStoreMockRecorder) AcquireCleanup(ctx, claim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireCleanup", reflect.TypeOf((*MockInstanceLeaseStore)(nil).AcquireCleanup), ctx, claim)
}

// Delete mocks base method.
func (m *MockInstanceLeaseStore) Delete(ctx context.Context, id realtime.InstanceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstanceLeaseStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstanceLeaseStore)(nil).Delete), ctx, id)
}

// Heartbeat mocks base method.
func (m *MockInstanceLeaseStore) Heartbeat(ctx context.Context, lease realtime.InstanceLease) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, lease)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockInstanceLeaseStoreMockRecorder) Heartbeat(ctx, lease any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockInstanceLeaseStore)(nil).Heartbeat), ctx, lease)
}

// ListExpired mocks base method.
func (m *MockInstanceLeaseStore) ListExpired(ctx context.Context, asOf time.Time) ([]realtime.InstanceLease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpired", ctx, asOf)
	ret0, _ := ret[0].([]realtime.InstanceLease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpired indicates an expected call of ListExpired.
func (mr *MockInstanceLeaseStoreMockRecorder) ListExpired(ctx, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpired", reflect.TypeOf((*MockInstanceLeaseStore)(nil).ListExpired), ctx, asOf)
}

// ReleaseCleanup mocks base method.
func (m *MockInstanceLeaseStore) ReleaseCleanup(ctx context.Context, release realtime.CleanupRelease) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCleanup", ctx, release)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseCleanup indicates an expected call of ReleaseCleanup.
func (mr *MockInstanceLeaseStoreMockRecorder) ReleaseCleanup(ctx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCleanup", reflect.TypeOf((*MockInstanceLeaseStore)(nil).ReleaseCleanup), ctx, release)
}
