// Code generated by MockGen. DO NOT EDIT.
// Source: revocation.go
//
// Generated by this command:
//
//	mockgen -source=revocation.go -destination=mock/mock_revocation.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRevocationNotifier is a mock of RevocationNotifier interface.
type MockRevocationNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRevocationNotifierMockRecorder
	isgomock struct{}
}

// MockRevocationNotifierMockRecorder is the mock recorder for MockRevocationNotifier.
type MockRevocationNotifierMockRecorder struct {
	mock *MockRevocationNotifier
}

// NewMockRevocationNotifier creates a new mock instance.
func NewMockRevocationNotifier(ctrl *gomock.Controller) *MockRevocationNotifier {
	mock := &MockRevocationNotifier{ctrl: ctrl}
	mock.recorder = &MockRevocationNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevocationNotifier) EXPECT() *MockRevocationNotifierMockRecorder {
	return m.recorder
}

// NotifyRevoked mocks base method.
func (m *MockRevocationNotifier) NotifyRevoked(ctx context.Context, subject string, destination realtime.StreamID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyRevoked", ctx, subject, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyRevoked indicates an expected call of NotifyRevoked.
func (mr *MockRevocationNotifierMockRecorder) NotifyRevoked(ctx, subject, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyRevoked", reflect.TypeOf((*MockRevocationNotifier)(nil).NotifyRevoked), ctx, subject, destination)
}
