// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock/mock_store.go.gen.go -package=mock_idempotency
//

// Package mock_idempotency is a generated GoMock package.
package mock_idempotency

import (
	context "context"
	idempotency "go-boilerplate/internal/usecase/boundary/idempotency"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MockStore) Claim(ctx context.Context, p idempotency.ClaimParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, p)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockStoreMockRecorder) Claim(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockStore)(nil).Claim), ctx, p)
}

// Complete mocks base method.
func (m *MockStore) Complete(ctx context.Context, p idempotency.CompleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockStoreMockRecorder) Complete(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockStore)(nil).Complete), ctx, p)
}

// DeleteExpired mocks base method.
func (m *MockStore) DeleteExpired(ctx context.Context, cutoff time.Time, limit int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, cutoff, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockStoreMockRecorder) DeleteExpired(ctx, cutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockStore)(nil).DeleteExpired), ctx, cutoff, limit)
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, scope, key string) (*idempotency.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, scope, key)
	ret0, _ := ret[0].(*idempotency.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, scope, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, scope, key)
}
