// Code generated by MockGen. DO NOT EDIT.
// Source: shutdown.go
//
// Generated by this command:
//
//	mockgen -source=shutdown.go -destination=mock/mock_shutdown.go.gen.go -package=mock_observability
//

// Package mock_observability is a generated GoMock package.
package mock_observability

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProviderShutdowner is a mock of ProviderShutdowner interface.
type MockProviderShutdowner struct {
	ctrl     *gomock.Controller
	recorder *MockProviderShutdownerMockRecorder
	isgomock struct{}
}

// MockProviderShutdownerMockRecorder is the mock recorder for MockProviderShutdowner.
type MockProviderShutdownerMockRecorder struct {
	mock *MockProviderShutdowner
}

// NewMockProviderShutdowner creates a new mock instance.
func NewMockProviderShutdowner(ctrl *gomock.Controller) *MockProviderShutdowner {
	mock := &MockProviderShutdowner{ctrl: ctrl}
	mock.recorder = &MockProviderShutdownerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderShutdowner) EXPECT() *MockProviderShutdownerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockProviderShutdowner) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockProviderShutdownerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockProviderShutdowner)(nil).Shutdown), ctx)
}
