// Code generated by MockGen. DO NOT EDIT.
// Source: layer_tracer.go
//
// Generated by this command:
//
//	mockgen -source=layer_tracer.go -destination=mock/mock_layer_tracer.go -package=mock_observability
//

// Package mock_observability is a generated GoMock package.
package mock_observability
