// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock/mock_provider.go -package=mock_observability
//

// Package mock_observability is a generated GoMock package.
package mock_observability
