// Code generated by MockGen. DO NOT EDIT.
// Source: tracer_factory.go
//
// Generated by this command:
//
//	mockgen -source=tracer_factory.go -destination=mock/mock_tracer_factory.gen.go -package=mock_observability
//

// Package mock_observability is a generated GoMock package.
package mock_observability

import (
	observability "go-boilerplate/internal/observability"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTracerFactory is a mock of TracerFactory interface.
type MockTracerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTracerFactoryMockRecorder
	isgomock struct{}
}

// MockTracerFactoryMockRecorder is the mock recorder for MockTracerFactory.
type MockTracerFactoryMockRecorder struct {
	mock *MockTracerFactory
}

// NewMockTracerFactory creates a new mock instance.
func NewMockTracerFactory(ctrl *gomock.Controller) *MockTracerFactory {
	mock := &MockTracerFactory{ctrl: ctrl}
	mock.recorder = &MockTracerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracerFactory) EXPECT() *MockTracerFactoryMockRecorder {
	return m.recorder
}

// Controller mocks base method.
func (m *MockTracerFactory) Controller() observability.LayerTracer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Controller")
	ret0, _ := ret[0].(observability.LayerTracer)
	return ret0
}

// Controller indicates an expected call of Controller.
func (mr *MockTracerFactoryMockRecorder) Controller() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controller", reflect.TypeOf((*MockTracerFactory)(nil).Controller))
}

// Infra mocks base method.
func (m *MockTracerFactory) Infra() observability.LayerTracer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Infra")
	ret0, _ := ret[0].(observability.LayerTracer)
	return ret0
}

// Infra indicates an expected call of Infra.
func (mr *MockTracerFactoryMockRecorder) Infra() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infra", reflect.TypeOf((*MockTracerFactory)(nil).Infra))
}

// Usecase mocks base method.
func (m *MockTracerFactory) Usecase() observability.LayerTracer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usecase")
	ret0, _ := ret[0].(observability.LayerTracer)
	return ret0
}

// Usecase indicates an expected call of Usecase.
func (mr *MockTracerFactoryMockRecorder) Usecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usecase", reflect.TypeOf((*MockTracerFactory)(nil).Usecase))
}
