// Code generated by MockGen. DO NOT EDIT.
// Source: lifecycle.go
//
// Generated by this command:
//
//	mockgen -source=lifecycle.go -destination=mock/mock_lifecycle.gen.go -package=mock_lifecycle
//

// Package mock_lifecycle is a generated GoMock package.
package mock_lifecycle

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrar is a mock of Registrar interface.
type MockRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrarMockRecorder
	isgomock struct{}
}

// MockRegistrarMockRecorder is the mock recorder for MockRegistrar.
type MockRegistrarMockRecorder struct {
	mock *MockRegistrar
}

// NewMockRegistrar creates a new mock instance.
func NewMockRegistrar(ctrl *gomock.Controller) *MockRegistrar {
	mock := &MockRegistrar{ctrl: ctrl}
	mock.recorder = &MockRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrar) EXPECT() *MockRegistrarMockRecorder {
	return m.recorder
}

// RegisterStart mocks base method.
func (m *MockRegistrar) RegisterStart(start func(context.Context) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterStart", start)
}

// RegisterStart indicates an expected call of RegisterStart.
func (mr *MockRegistrarMockRecorder) RegisterStart(start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterStart", reflect.TypeOf((*MockRegistrar)(nil).RegisterStart), start)
}

// RegisterStop mocks base method.
func (m *MockRegistrar) RegisterStop(stop func(context.Context) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterStop", stop)
}

// RegisterStop indicates an expected call of RegisterStop.
func (mr *MockRegistrarMockRecorder) RegisterStop(stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterStop", reflect.TypeOf((*MockRegistrar)(nil).RegisterStop), stop)
}
