// Code generated by MockGen. DO NOT EDIT.
// Source: common.go
//
// Generated by this command:
//
//	mockgen -source=common.go -destination=mock/mock_common.go -package=mock_migrate
//

// Package mock_migrate is a generated GoMock package.
package mock_migrate

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMigrator is a mock of Migrator interface.
type MockMigrator struct {
	ctrl     *gomock.Controller
	recorder *MockMigratorMockRecorder
	isgomock struct{}
}

// MockMigratorMockRecorder is the mock recorder for MockMigrator.
type MockMigratorMockRecorder struct {
	mock *MockMigrator
}

// NewMockMigrator creates a new mock instance.
func NewMockMigrator(ctrl *gomock.Controller) *MockMigrator {
	mock := &MockMigrator{ctrl: ctrl}
	mock.recorder = &MockMigratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrator) EXPECT() *MockMigratorMockRecorder {
	return m.recorder
}

// Down mocks base method.
func (m *MockMigrator) Down() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Down")
	ret0, _ := ret[0].(error)
	return ret0
}

// Down indicates an expected call of Down.
func (mr *MockMigratorMockRecorder) Down() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Down", reflect.TypeOf((*MockMigrator)(nil).Down))
}

// Force mocks base method.
func (m *MockMigrator) Force(version int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Force", version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Force indicates an expected call of Force.
func (mr *MockMigratorMockRecorder) Force(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Force", reflect.TypeOf((*MockMigrator)(nil).Force), version)
}

// Steps mocks base method.
func (m *MockMigrator) Steps(n int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Steps", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Steps indicates an expected call of Steps.
func (mr *MockMigratorMockRecorder) Steps(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Steps", reflect.TypeOf((*MockMigrator)(nil).Steps), n)
}

// Up mocks base method.
func (m *MockMigrator) Up() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Up")
	ret0, _ := ret[0].(error)
	return ret0
}

// Up indicates an expected call of Up.
func (mr *MockMigratorMockRecorder) Up() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockMigrator)(nil).Up))
}

// Version mocks base method.
func (m *MockMigrator) Version() (uint, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Version indicates an expected call of Version.
func (mr *MockMigratorMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockMigrator)(nil).Version))
}
