// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/fx (interfaces: Shutdowner)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_fx.gen.go -package=mock_shutdowner -mock_names=Shutdowner=MockFxShutdowner go.uber.org/fx Shutdowner
//

// Package mock_shutdowner is a generated GoMock package.
package mock_shutdowner

import (
	reflect "reflect"

	fx "go.uber.org/fx"
	gomock "go.uber.org/mock/gomock"
)

// MockFxShutdowner is a mock of Shutdowner interface.
type MockFxShutdowner struct {
	ctrl     *gomock.Controller
	recorder *MockFxShutdownerMockRecorder
	isgomock struct{}
}

// MockFxShutdownerMockRecorder is the mock recorder for MockFxShutdowner.
type MockFxShutdownerMockRecorder struct {
	mock *MockFxShutdowner
}

// NewMockFxShutdowner creates a new mock instance.
func NewMockFxShutdowner(ctrl *gomock.Controller) *MockFxShutdowner {
	mock := &MockFxShutdowner{ctrl: ctrl}
	mock.recorder = &MockFxShutdownerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFxShutdowner) EXPECT() *MockFxShutdownerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockFxShutdowner) Shutdown(arg0 ...fx.ShutdownOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Shutdown", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockFxShutdownerMockRecorder) Shutdown(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockFxShutdowner)(nil).Shutdown), arg0...)
}
