// Code generated by MockGen. DO NOT EDIT.
// Source: shutdowner.go
//
// Generated by this command:
//
//	mockgen -source=shutdowner.go -destination=mock/mock_shutdowner.go -package=mock_shutdowner
//

// Package mock_shutdowner is a generated GoMock package.
package mock_shutdowner

import (
	reflect "reflect"

	fx "go.uber.org/fx"
	gomock "go.uber.org/mock/gomock"
)

// MockShutdowner is a mock of Shutdowner interface.
type MockShutdowner struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownerMockRecorder
	isgomock struct{}
}

// MockShutdownerMockRecorder is the mock recorder for MockShutdowner.
type MockShutdownerMockRecorder struct {
	mock *MockShutdowner
}

// NewMockShutdowner creates a new mock instance.
func NewMockShutdowner(ctrl *gomock.Controller) *MockShutdowner {
	mock := &MockShutdowner{ctrl: ctrl}
	mock.recorder = &MockShutdownerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdowner) EXPECT() *MockShutdownerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockShutdowner) Shutdown(opt ...fx.ShutdownOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opt {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Shutdown", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockShutdownerMockRecorder) Shutdown(opt ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockShutdowner)(nil).Shutdown), opt...)
}
