// Code generated by MockGen. DO NOT EDIT.
// Source: health_check_system_cqrs.go
//
// Generated by this command:
//
//	mockgen -source=health_check_system_cqrs.go -destination=mock/mock_health_check_system_cqrs.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/healthcheck/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBSystemCqrs is a mock of DBSystemCqrs interface.
type MockDBSystemCqrs struct {
	ctrl     *gomock.Controller
	recorder *MockDBSystemCqrsMockRecorder
	isgomock struct{}
}

// MockDBSystemCqrsMockRecorder is the mock recorder for MockDBSystemCqrs.
type MockDBSystemCqrsMockRecorder struct {
	mock *MockDBSystemCqrs
}

// NewMockDBSystemCqrs creates a new mock instance.
func NewMockDBSystemCqrs(ctrl *gomock.Controller) *MockDBSystemCqrs {
	mock := &MockDBSystemCqrs{ctrl: ctrl}
	mock.recorder = &MockDBSystemCqrsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBSystemCqrs) EXPECT() *MockDBSystemCqrsMockRecorder {
	return m.recorder
}

// CheckDBHealth mocks base method.
func (m *MockDBSystemCqrs) CheckDBHealth(ctx context.Context) (query.DBHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDBHealth", ctx)
	ret0, _ := ret[0].(query.DBHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDBHealth indicates an expected call of CheckDBHealth.
func (mr *MockDBSystemCqrsMockRecorder) CheckDBHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDBHealth", reflect.TypeOf((*MockDBSystemCqrs)(nil).CheckDBHealth), ctx)
}
