// Code generated by MockGen. DO NOT EDIT.
// Source: health_check_system_query.go
//
// Generated by this command:
//
//	mockgen -source=health_check_system_query.go -destination=mock/mock_health_check_system_query.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/healthcheck/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBSystemQuery is a mock of DBSystemQuery interface.
type MockDBSystemQuery struct {
	ctrl     *gomock.Controller
	recorder *MockDBSystemQueryMockRecorder
	isgomock struct{}
}

// MockDBSystemQueryMockRecorder is the mock recorder for MockDBSystemQuery.
type MockDBSystemQueryMockRecorder struct {
	mock *MockDBSystemQuery
}

// NewMockDBSystemQuery creates a new mock instance.
func NewMockDBSystemQuery(ctrl *gomock.Controller) *MockDBSystemQuery {
	mock := &MockDBSystemQuery{ctrl: ctrl}
	mock.recorder = &MockDBSystemQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBSystemQuery) EXPECT() *MockDBSystemQueryMockRecorder {
	return m.recorder
}

// CheckDBHealth mocks base method.
func (m *MockDBSystemQuery) CheckDBHealth(ctx context.Context) (query.DBHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDBHealth", ctx)
	ret0, _ := ret[0].(query.DBHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDBHealth indicates an expected call of CheckDBHealth.
func (mr *MockDBSystemQueryMockRecorder) CheckDBHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDBHealth", reflect.TypeOf((*MockDBSystemQuery)(nil).CheckDBHealth), ctx)
}
