// Code generated by MockGen. DO NOT EDIT.
// Source: buildinfo.go
//
// Generated by this command:
//
//	mockgen -source=buildinfo.go -destination=mock/mock_buildinfo.go.gen.go -package=mock_system
//

// Package mock_system is a generated GoMock package.
package mock_system

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBuildInfo is a mock of BuildInfo interface.
type MockBuildInfo struct {
	ctrl     *gomock.Controller
	recorder *MockBuildInfoMockRecorder
	isgomock struct{}
}

// MockBuildInfoMockRecorder is the mock recorder for MockBuildInfo.
type MockBuildInfoMockRecorder struct {
	mock *MockBuildInfo
}

// NewMockBuildInfo creates a new mock instance.
func NewMockBuildInfo(ctrl *gomock.Controller) *MockBuildInfo {
	mock := &MockBuildInfo{ctrl: ctrl}
	mock.recorder = &MockBuildInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildInfo) EXPECT() *MockBuildInfoMockRecorder {
	return m.recorder
}

// BuildDate mocks base method.
func (m *MockBuildInfo) BuildDate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildDate")
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildDate indicates an expected call of BuildDate.
func (mr *MockBuildInfoMockRecorder) BuildDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildDate", reflect.TypeOf((*MockBuildInfo)(nil).BuildDate))
}

// Revision mocks base method.
func (m *MockBuildInfo) Revision() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revision")
	ret0, _ := ret[0].(string)
	return ret0
}

// Revision indicates an expected call of Revision.
func (mr *MockBuildInfoMockRecorder) Revision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revision", reflect.TypeOf((*MockBuildInfo)(nil).Revision))
}

// Version mocks base method.
func (m *MockBuildInfo) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockBuildInfoMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockBuildInfo)(nil).Version))
}
