import { describe, expect, it } from "vitest";

import { hasPremisePhrase, inspect, isChecked } from "./rules";

describe("isChecked", () => {
  describe("正常系", () => {
    it("fork 後も残る文書を対象にする", () => {
      expect(isChecked("docs/adr/0001-avoid-lock-in.md")).toBe(true);
      expect(isChecked("docs/rules.md")).toBe(true);
      expect(isChecked("docs/design/worker.md")).toBe(true);
      expect(isChecked(".makefiles/README.md")).toBe(true);
    });

    it("層 README を対象にする", () => {
      expect(isChecked("internal/domain/README.md")).toBe(true);
      expect(isChecked("pkg/uuid/README.ja.md")).toBe(true);
    });

    // ミラーは正本と同じ内容を運ぶので、正本が対象ならミラーも対象。
    it("日本語ミラーを正本と同じ扱いにする", () => {
      expect(isChecked("docs/ja/adr/0001-avoid-lock-in.ja.md")).toBe(true);
      expect(isChecked("docs/ja/rules.ja.md")).toBe(true);
    });
  });

  describe("異常系", () => {
    // 許可域は前提と一緒に消えるので、前提が残っても嘘にならない。
    it("許可域を対象から外す", () => {
      expect(isChecked("README.md")).toBe(false);
      expect(isChecked("README.ja.md")).toBe(false);
      expect(isChecked("docs/get-started/setup-repository.md")).toBe(false);
      expect(isChecked("docs/ja/get-started/setup-repository.ja.md")).toBe(false);
    });

    it("Markdown 以外を対象にしない", () => {
      expect(isChecked("internal/domain/user/user_domain.go")).toBe(false);
      expect(isChecked("docs/portal/manifest.yaml")).toBe(false);
    });

    it("挙げていない領域を対象にしない", () => {
      expect(isChecked("docs/deployment/github-page.md")).toBe(false);
      expect(isChecked("scripts/README.md")).toBe(false);
    });
  });
});

describe("hasPremisePhrase", () => {
  describe("正常系", () => {
    it("自己参照の言い回しを検出する", () => {
      expect(hasPremisePhrase("This template targets backend services.")).toBe(true);
      expect(hasPremisePhrase("The scaffold provides the runner.")).toBe(true);
      expect(hasPremisePhrase("Adopters must configure rate limiting.")).toBe(true);
      expect(hasPremisePhrase("A template-derived repository starts disabled.")).toBe(true);
      expect(hasPremisePhrase("このテンプレートは Onion Architecture を前提とする")).toBe(true);
      expect(hasPremisePhrase("本テンプレートは `http.Server` を自前で持つ")).toBe(true);
    });
  });

  describe("異常系", () => {
    // 裸の名詞で落とすと 381 件が当たり、その大半が別語義だった。判定は自己参照の形に限る。
    it("裸の名詞だけでは検出しない", () => {
      expect(hasPremisePhrase("More boilerplate than an ORM's convenience methods.")).toBe(false);
      expect(hasPremisePhrase("Downstream consumers observe eventual consistency.")).toBe(false);
      expect(hasPremisePhrase("Generated by the `scaffold-domain` skill.")).toBe(false);
      expect(hasPremisePhrase("Rendered with Go `text/template`.")).toBe(false);
    });

    it("上流サービスの意味の upstream を検出しない", () => {
      expect(hasPremisePhrase("The upstream HTTP service returns 503.")).toBe(false);
    });
  });
});

describe("inspect", () => {
  describe("正常系", () => {
    it("該当行を行番号付きで返す", () => {
      const content = ["# Title", "", "This template targets X.", "Normal line."].join("\n");

      expect(inspect("docs/rules.md", content, [])).toEqual([
        { file: "docs/rules.md", line: 3, text: "This template targets X." },
      ]);
    });

    it("該当が無ければ空を返す", () => {
      expect(inspect("docs/rules.md", "# Title\n\nNormal.", [])).toEqual([]);
    });

    // 宣言は本文の一部で綴じる。行が動いても効き続け、どの記述を許したかが宣言だけで読める。
    it("宣言された行を除外する", () => {
      const content = "CREATE DATABASE ... TEMPLATE template1 while the template is stale";
      const allowances = [
        { file: "a/README.md", contains: "TEMPLATE template1", reason: "PostgreSQL の template DB" },
      ];

      expect(inspect("a/README.md", content, allowances)).toEqual([]);
    });
  });

  describe("異常系", () => {
    // 宣言はファイル単位で効く。別ファイルの同文を巻き添えで許すと、検査に穴が開く。
    it("別ファイルの宣言では除外しない", () => {
      const content = "This template targets X.";
      const allowances = [{ file: "other.md", contains: "This template", reason: "別物" }];

      expect(inspect("docs/rules.md", content, allowances)).toHaveLength(1);
    });
  });
});
