// Code generated by MockGen. DO NOT EDIT.
// Source: ticket.go
//
// Generated by this command:
//
//	mockgen -source=ticket.go -destination=mock/mock_ticket.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	realtime0 "go-boilerplate/internal/usecase/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTicketIssuer is a mock of TicketIssuer interface.
type MockTicketIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTicketIssuerMockRecorder
	isgomock struct{}
}

// MockTicketIssuerMockRecorder is the mock recorder for MockTicketIssuer.
type MockTicketIssuerMockRecorder struct {
	mock *MockTicketIssuer
}

// NewMockTicketIssuer creates a new mock instance.
func NewMockTicketIssuer(ctrl *gomock.Controller) *MockTicketIssuer {
	mock := &MockTicketIssuer{ctrl: ctrl}
	mock.recorder = &MockTicketIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketIssuer) EXPECT() *MockTicketIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTicketIssuer) Issue(ctx context.Context, in realtime0.IssueTicketInput) (realtime0.TicketView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, in)
	ret0, _ := ret[0].(realtime0.TicketView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockTicketIssuerMockRecorder) Issue(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTicketIssuer)(nil).Issue), ctx, in)
}

// MockTicketVerifier is a mock of TicketVerifier interface.
type MockTicketVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockTicketVerifierMockRecorder
	isgomock struct{}
}

// MockTicketVerifierMockRecorder is the mock recorder for MockTicketVerifier.
type MockTicketVerifierMockRecorder struct {
	mock *MockTicketVerifier
}

// NewMockTicketVerifier creates a new mock instance.
func NewMockTicketVerifier(ctrl *gomock.Controller) *MockTicketVerifier {
	mock := &MockTicketVerifier{ctrl: ctrl}
	mock.recorder = &MockTicketVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketVerifier) EXPECT() *MockTicketVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockTicketVerifier) Verify(ctx context.Context, value string, destination realtime.StreamID) (realtime.StreamGrant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, value, destination)
	ret0, _ := ret[0].(realtime.StreamGrant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockTicketVerifierMockRecorder) Verify(ctx, value, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTicketVerifier)(nil).Verify), ctx, value, destination)
}
