// Code generated by MockGen. DO NOT EDIT.
// Source: lease.go
//
// Generated by this command:
//
//	mockgen -source=lease.go -destination=mock/mock_lease.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLeaseKeeper is a mock of LeaseKeeper interface.
type MockLeaseKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseKeeperMockRecorder
	isgomock struct{}
}

// MockLeaseKeeperMockRecorder is the mock recorder for MockLeaseKeeper.
type MockLeaseKeeperMockRecorder struct {
	mock *MockLeaseKeeper
}

// NewMockLeaseKeeper creates a new mock instance.
func NewMockLeaseKeeper(ctrl *gomock.Controller) *MockLeaseKeeper {
	mock := &MockLeaseKeeper{ctrl: ctrl}
	mock.recorder = &MockLeaseKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaseKeeper) EXPECT() *MockLeaseKeeperMockRecorder {
	return m.recorder
}

// Beat mocks base method.
func (m *MockLeaseKeeper) Beat(ctx context.Context, id realtime.InstanceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Beat", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Beat indicates an expected call of Beat.
func (mr *MockLeaseKeeperMockRecorder) Beat(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Beat", reflect.TypeOf((*MockLeaseKeeper)(nil).Beat), ctx, id)
}

// Release mocks base method.
func (m *MockLeaseKeeper) Release(ctx context.Context, id realtime.InstanceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockLeaseKeeperMockRecorder) Release(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLeaseKeeper)(nil).Release), ctx, id)
}
