// Code generated by MockGen. DO NOT EDIT.
// Source: cleanup.go
//
// Generated by this command:
//
//	mockgen -source=cleanup.go -destination=mock/mock_cleanup.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrphanSweeper is a mock of OrphanSweeper interface.
type MockOrphanSweeper struct {
	ctrl     *gomock.Controller
	recorder *MockOrphanSweeperMockRecorder
	isgomock struct{}
}

// MockOrphanSweeperMockRecorder is the mock recorder for MockOrphanSweeper.
type MockOrphanSweeperMockRecorder struct {
	mock *MockOrphanSweeper
}

// NewMockOrphanSweeper creates a new mock instance.
func NewMockOrphanSweeper(ctrl *gomock.Controller) *MockOrphanSweeper {
	mock := &MockOrphanSweeper{ctrl: ctrl}
	mock.recorder = &MockOrphanSweeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrphanSweeper) EXPECT() *MockOrphanSweeperMockRecorder {
	return m.recorder
}

// Sweep mocks base method.
func (m *MockOrphanSweeper) Sweep(ctx context.Context) (realtime.SweepResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sweep", ctx)
	ret0, _ := ret[0].(realtime.SweepResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sweep indicates an expected call of Sweep.
func (mr *MockOrphanSweeperMockRecorder) Sweep(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sweep", reflect.TypeOf((*MockOrphanSweeper)(nil).Sweep), ctx)
}
