// Code generated by MockGen. DO NOT EDIT.
// Source: replay.go
//
// Generated by this command:
//
//	mockgen -source=replay.go -destination=mock/mock_replay.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReplayer is a mock of Replayer interface.
type MockReplayer struct {
	ctrl     *gomock.Controller
	recorder *MockReplayerMockRecorder
	isgomock struct{}
}

// MockReplayerMockRecorder is the mock recorder for MockReplayer.
type MockReplayerMockRecorder struct {
	mock *MockReplayer
}

// NewMockReplayer creates a new mock instance.
func NewMockReplayer(ctrl *gomock.Controller) *MockReplayer {
	mock := &MockReplayer{ctrl: ctrl}
	mock.recorder = &MockReplayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayer) EXPECT() *MockReplayerMockRecorder {
	return m.recorder
}

// ReadPage mocks base method.
func (m *MockReplayer) ReadPage(ctx context.Context, streamID realtime.StreamID, after realtime.Sequence) ([]realtime.DeliveryEvent, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", ctx, streamID, after)
	ret0, _ := ret[0].([]realtime.DeliveryEvent)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadPage indicates an expected call of ReadPage.
func (mr *MockReplayerMockRecorder) ReadPage(ctx, streamID, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*MockReplayer)(nil).ReadPage), ctx, streamID, after)
}
