// Code generated by MockGen. DO NOT EDIT.
// Source: revocation.go
//
// Generated by this command:
//
//	mockgen -source=revocation.go -destination=mock/mock_revocation.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessRevoker is a mock of AccessRevoker interface.
type MockAccessRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockAccessRevokerMockRecorder
	isgomock struct{}
}

// MockAccessRevokerMockRecorder is the mock recorder for MockAccessRevoker.
type MockAccessRevokerMockRecorder struct {
	mock *MockAccessRevoker
}

// NewMockAccessRevoker creates a new mock instance.
func NewMockAccessRevoker(ctrl *gomock.Controller) *MockAccessRevoker {
	mock := &MockAccessRevoker{ctrl: ctrl}
	mock.recorder = &MockAccessRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessRevoker) EXPECT() *MockAccessRevokerMockRecorder {
	return m.recorder
}

// Revoke mocks base method.
func (m *MockAccessRevoker) Revoke(ctx context.Context, subject string, destination realtime.StreamID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, subject, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAccessRevokerMockRecorder) Revoke(ctx, subject, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAccessRevoker)(nil).Revoke), ctx, subject, destination)
}
