// Code generated by MockGen. DO NOT EDIT.
// Source: cursor.go
//
// Generated by this command:
//
//	mockgen -source=cursor.go -destination=mock/mock_cursor.go.gen.go -package=mock_realtime
//

// Package mock_realtime is a generated GoMock package.
package mock_realtime

import (
	context "context"
	realtime "go-boilerplate/internal/usecase/boundary/realtime"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCursorValidator is a mock of CursorValidator interface.
type MockCursorValidator struct {
	ctrl     *gomock.Controller
	recorder *MockCursorValidatorMockRecorder
	isgomock struct{}
}

// MockCursorValidatorMockRecorder is the mock recorder for MockCursorValidator.
type MockCursorValidatorMockRecorder struct {
	mock *MockCursorValidator
}

// NewMockCursorValidator creates a new mock instance.
func NewMockCursorValidator(ctrl *gomock.Controller) *MockCursorValidator {
	mock := &MockCursorValidator{ctrl: ctrl}
	mock.recorder = &MockCursorValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursorValidator) EXPECT() *MockCursorValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockCursorValidator) Validate(ctx context.Context, streamID realtime.StreamID, cursor realtime.Sequence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, streamID, cursor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockCursorValidatorMockRecorder) Validate(ctx, streamID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCursorValidator)(nil).Validate), ctx, streamID, cursor)
}
