// Code generated by MockGen. DO NOT EDIT.
// Source: product_discontinue_command_service.go
//
// Generated by this command:
//
//	mockgen -source=product_discontinue_command_service.go -destination=mock/mock_product_discontinue_command_service.go.gen.go -package=mock_command
//

// Package mock_command is a generated GoMock package.
package mock_command

import (
	context "context"
	command "go-boilerplate/internal/usecase/product/command"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandService is a mock of CommandService interface.
type MockCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockCommandServiceMockRecorder
	isgomock struct{}
}

// MockCommandServiceMockRecorder is the mock recorder for MockCommandService.
type MockCommandServiceMockRecorder struct {
	mock *MockCommandService
}

// NewMockCommandService creates a new mock instance.
func NewMockCommandService(ctrl *gomock.Controller) *MockCommandService {
	mock := &MockCommandService{ctrl: ctrl}
	mock.recorder = &MockCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandService) EXPECT() *MockCommandServiceMockRecorder {
	return m.recorder
}

// IssueDiscontinuationCoupons mocks base method.
func (m *MockCommandService) IssueDiscontinuationCoupons(ctx context.Context, params command.IssueDiscontinuationCouponsParams) (command.IssueDiscontinuationCouponsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueDiscontinuationCoupons", ctx, params)
	ret0, _ := ret[0].(command.IssueDiscontinuationCouponsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueDiscontinuationCoupons indicates an expected call of IssueDiscontinuationCoupons.
func (mr *MockCommandServiceMockRecorder) IssueDiscontinuationCoupons(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueDiscontinuationCoupons", reflect.TypeOf((*MockCommandService)(nil).IssueDiscontinuationCoupons), ctx, params)
}
