// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestWithDbTimeout(t *testing.T) {
	t.Parallel()

	base := context.Background()
	ctx := context.WithValue(base, dbtimeoutKey, *new(time.Duration))

	val := ctx.Value(dbtimeoutKey)
	require.NotNil(t, val)
	v, ok := val.(time.Duration)
	require.True(t, ok)
	require.Equal(t, *new(time.Duration), v)
}

func TestDbTimeoutFromContext(t *testing.T) {
	t.Parallel()

	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = WithDbTimeout(ctx, *new(time.Duration))

		val, ok := DbTimeoutFromContext(ctx)
		require.True(t, ok)
		require.Equal(t, *new(time.Duration), val)
	})

	t.Run("standard context - no value", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := DbTimeoutFromContext(ctx)
		require.False(t, ok)
		require.Equal(t, *new(time.Duration), val)
	})
}
