// Package ctxhelper is provides utilities for securely maintaining metadata
// during request processing for Echo and the standard context.Context.
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
	"time"
)

type dbtimeoutKeyType struct{}

var dbtimeoutKey = dbtimeoutKeyType{}

func WithDbTimeout(ctx context.Context, val time.Duration) context.Context {
	return context.WithValue(ctx, dbtimeoutKey, val)
}

func DbTimeoutFromContext(ctx context.Context) (time.Duration, bool) {
	val := ctx.Value(dbtimeoutKey)
	if v, ok := val.(time.Duration); ok {
		return v, true
	}
	return *new(time.Duration), false
}
