// Code generated by MockGen. DO NOT EDIT.
// Source: inquiry_repository.go
//
// Generated by this command:
//
//	mockgen -source=inquiry_repository.go -destination=mock/mock_inquiry_repository.go.gen.go -package=mock_inquiry
//

// Package mock_inquiry is a generated GoMock package.
package mock_inquiry

import (
	context "context"
	inquiry "go-boilerplate/internal/domain/inquiry"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateIfAbsent mocks base method.
func (m *MockRepository) CreateIfAbsent(ctx context.Context, arg1 *inquiry.Inquiry) (*inquiry.Inquiry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfAbsent", ctx, arg1)
	ret0, _ := ret[0].(*inquiry.Inquiry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIfAbsent indicates an expected call of CreateIfAbsent.
func (mr *MockRepositoryMockRecorder) CreateIfAbsent(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfAbsent", reflect.TypeOf((*MockRepository)(nil).CreateIfAbsent), ctx, arg1)
}

// CreateMessage mocks base method.
func (m *MockRepository) CreateMessage(ctx context.Context, inquiryID uuid.UUID, message *inquiry.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, inquiryID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockRepositoryMockRecorder) CreateMessage(ctx, inquiryID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockRepository)(nil).CreateMessage), ctx, inquiryID, message)
}

// FindActiveByUserID mocks base method.
func (m *MockRepository) FindActiveByUserID(ctx context.Context, userID uuid.UUID) (*inquiry.Inquiry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(*inquiry.Inquiry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByUserID indicates an expected call of FindActiveByUserID.
func (mr *MockRepositoryMockRecorder) FindActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByUserID", reflect.TypeOf((*MockRepository)(nil).FindActiveByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*inquiry.Inquiry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*inquiry.Inquiry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// ListForOperator mocks base method.
func (m *MockRepository) ListForOperator(ctx context.Context, params inquiry.ListParams) ([]*inquiry.Inquiry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForOperator", ctx, params)
	ret0, _ := ret[0].([]*inquiry.Inquiry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForOperator indicates an expected call of ListForOperator.
func (mr *MockRepositoryMockRecorder) ListForOperator(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForOperator", reflect.TypeOf((*MockRepository)(nil).ListForOperator), ctx, params)
}

// ListMessages mocks base method.
func (m *MockRepository) ListMessages(ctx context.Context, inquiryID uuid.UUID, params inquiry.HistoryParams) ([]*inquiry.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, inquiryID, params)
	ret0, _ := ret[0].([]*inquiry.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockRepositoryMockRecorder) ListMessages(ctx, inquiryID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockRepository)(nil).ListMessages), ctx, inquiryID, params)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, arg1 *inquiry.Inquiry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, arg1)
}
