#!/usr/bin/env bash
set -euo pipefail

# 出力先（例：ドキュメント配下にメタ情報として置く）
OUTPUT_FILE="docs/meta/generator-versions.txt"
MODE="${1:-all}"

header() {
  echo "### Generator tools versions"
  echo ""
  echo "generated by scripts/gen_tools_version.sh"
}

normalize() {
  printf "%s" "$1" | tr '\n' ' ' | tr -s ' '
}

go_section() {
  echo ""
  echo "**Go-based tools (go_tool_runner)**"
  echo ""
  echo "- golang-migrate: $(normalize "$(migrate -version 2>&1 || echo 'unknown')")"
  echo "- mockgen: $(normalize "$(mockgen -version 2>&1 || echo 'unknown')")"
  echo "- oapi-codegen: $(normalize "$(oapi-codegen --version 2>&1 || echo 'unknown')")"
  echo "- sqlc: $(normalize "$(sqlc version 2>&1 || echo 'unknown')")"
}

node_section() {
  echo ""
  echo "**Node-based tools (node_tool_runner)**"
  echo ""
  echo "- redocly: $(normalize "$(redocly --version 2>&1 || echo 'unknown')")"
}

python_section() {
  local py="python"
  if ! command -v python >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
    py="python3"
  fi

  local pip="pip"
  if ! command -v pip >/dev/null 2>&1 && command -v pip3 >/dev/null 2>&1; then
    pip="pip3"
  fi

  echo ""
  echo "**Python-based tools (python_tool_runner)**"
  echo ""
  echo "- sqlfluff: $(normalize "$(sqlfluff --version 2>&1 || "${py}" -m sqlfluff --version 2>&1 || "${py}" -c 'import sqlfluff; print(sqlfluff.__version__)' 2>/dev/null || echo 'unknown')")"
}

case "$MODE" in
  go)
    {
      header
      go_section
    } > "$OUTPUT_FILE"
    ;;
  node)
    {
      # go 側がまだ生成されてないケースも考えて、ファイルが無ければヘッダを書く
      if [ ! -f "$OUTPUT_FILE" ]; then
        header
      fi
      node_section
    } >> "$OUTPUT_FILE"
    ;;
  python)
    {
      # go/node 側がまだ生成されてないケースも考えて、ファイルが無ければヘッダを書く
      if [ ! -f "$OUTPUT_FILE" ]; then
        header
      fi
      python_section
    } >> "$OUTPUT_FILE"
    ;;
  *)
    {
      header
      go_section
      node_section
    python_section
    } > "$OUTPUT_FILE"
    ;;
esac
