#!/usr/bin/env bash
set -euo pipefail

# 出力先（例：ドキュメント配下にメタ情報として置く）
OUTPUT_FILE="docs/meta/generator-versions.txt"
MODE="${1:-all}"

header() {
  echo "### Generator tools versions"
  echo ""
  echo "generated by scripts/gen_generator_versions.sh"
}

normalize() {
  printf "%s" "$1" | tr '\n' ' ' | tr -s ' '
}

go_section() {
  echo ""
  echo "**Go-based tools (go_tool_runner)**"
  echo ""
  echo "- golang-migrate: $(normalize "$(migrate -version 2>&1 || echo 'unknown')")"
  echo "- mockgen: $(normalize "$(mockgen -version 2>&1 || echo 'unknown')")"
  echo "- oapi-codegen: $(normalize "$(oapi-codegen --version 2>&1 || echo 'unknown')")"
  echo "- sqlc: $(normalize "$(sqlc version 2>&1 || echo 'unknown')")"
}

node_section() {
  echo ""
  echo "**Node-based tools (node_tool_runner)**"
  echo ""
  echo "- swagger-cli: $(normalize "$(swagger-cli --version 2>&1 || echo 'unknown')")"
  echo "- redocly: $(normalize "$(redocly --version 2>&1 || echo 'unknown')")"
}

case "$MODE" in
  go)
    {
      header
      go_section
    } > "$OUTPUT_FILE"
    ;;
  node)
    {
      # go 側がまだ生成されてないケースも考えて、ファイルが無ければヘッダを書く
      if [ ! -f "$OUTPUT_FILE" ]; then
        header
      fi
      node_section
    } >> "$OUTPUT_FILE"
    ;;
  *)
    {
      header
      go_section
      node_section
    } > "$OUTPUT_FILE"
    ;;
esac
