#!/bin/bash
set -e

NAME_INPUT=$1  # e.g. UserID
TYPE_INPUT=$2  # e.g. string

NAME_LOWER=$(echo "$NAME_INPUT" | tr '[:upper:]' '[:lower:]')
NAME_MIXED=$(echo "$NAME_INPUT" | sed -E 's/([a-z])([A-Z])/\1_\2/g' | tr '[:upper:]' '[:lower:]')
NAME_CAMEL=$(echo "$NAME_INPUT" | sed -E 's/(^|_)([a-z])/\U\2/g')

OUT_DIR="internal/controller/ctxhelper"
OUT_FILE="${OUT_DIR}/${NAME_MIXED}_ctx.go"
TEST_FILE="${OUT_DIR}/${NAME_MIXED}_ctx_test.go"

# テスト用の型別値設定
case "${TYPE_INPUT}" in
  string)
    TEST_VALUE='"test-'${NAME_LOWER}'"'
    ;;
  int)
    TEST_VALUE=123
    ;;
  bool)
    TEST_VALUE=true
    ;;
  *)
    TEST_VALUE='*new(${TYPE_INPUT})'
    ;;
esac

# Go本体生成
cat <<EOF > $OUT_FILE
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxHelper

import (
	"context"

	"github.com/labstack/echo/v4"
)

type ${NAME_LOWER}KeyType struct{}

var ${NAME_LOWER}Key = ${NAME_LOWER}KeyType{}

// --- std lib context ---

func Set${NAME_CAMEL}(ctx context.Context, val ${TYPE_INPUT}) context.Context {
	return context.WithValue(ctx, ${NAME_LOWER}Key, val)
}

func Get${NAME_CAMEL}(ctx context.Context) (${TYPE_INPUT}, bool) {
	val := ctx.Value(${NAME_LOWER}Key)
	if v, ok := val.(${TYPE_INPUT}); ok {
		return v, true
	}
	return *new(${TYPE_INPUT}), false
}

// --- echo.Context wrapper ---

func Set${NAME_CAMEL}ToEcho(c echo.Context, val ${TYPE_INPUT}) {
	ctx := context.WithValue(c.Request().Context(), ${NAME_LOWER}Key, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func Get${NAME_CAMEL}FromEcho(c echo.Context) (${TYPE_INPUT}, bool) {
	val := c.Request().Context().Value(${NAME_LOWER}Key)
	if v, ok := val.(${TYPE_INPUT}); ok {
		return v, true
	}
	return *new(${TYPE_INPUT}), false
}
EOF

cat <<EOF > $TEST_FILE
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxHelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
)

func Test${NAME_CAMEL}Context(t *testing.T) {
	t.Parallel()
	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = Set${NAME_CAMEL}(ctx, ${TEST_VALUE})

		val, ok := Get${NAME_CAMEL}(ctx)
		assert.True(t, ok)
		assert.Equal(t, ${TEST_VALUE}, val)
	})

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		req := httptest.NewRequest(http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		Set${NAME_CAMEL}ToEcho(c, ${TEST_VALUE})
		val, ok := Get${NAME_CAMEL}FromEcho(c)

		assert.True(t, ok)
		assert.Equal(t, ${TEST_VALUE}, val)
	})
}
EOF

echo "✅ Generated: ${OUT_FILE}"
echo "✅ Generated: ${TEST_FILE}"
