#!/bin/bash
set -e

NAME_INPUT=$1  # e.g. UserID
TYPE_INPUT=$2  # e.g. string

NAME_LOWER=$(echo "$NAME_INPUT" | tr '[:upper:]' '[:lower:]')
NAME_MIXED=$(echo "$NAME_INPUT" | sed -E 's/([a-z])([A-Z])/\1_\2/g' | tr '[:upper:]' '[:lower:]')
NAME_CAMEL=$(
  echo "$NAME_MIXED" \
  | awk -F'_' '{
      for (i = 1; i <= NF; i++) {
        $i = toupper(substr($i, 1, 1)) substr($i, 2)
      }
      OFS = ""
      print
    }' \
  | tr -d '[:space:]'
)

OUT_DIR="internal/ctxhelper"
OUT_FILE="${OUT_DIR}/${NAME_MIXED}_ctx.go"
TEST_FILE="${OUT_DIR}/${NAME_MIXED}_ctx_test.go"

# テスト用の型別値設定
case "${TYPE_INPUT}" in
  string)
    TEST_SUCCESS_VALUE='"test-'${NAME_LOWER}'"'
	TEST_FAIL_VALUE='""'
    ;;
  int)
    TEST_SUCCESS_VALUE=123
	TEST_FAIL_VALUE=0
    ;;
  bool)
    TEST_SUCCESS_VALUE=true
	TEST_FAIL_VALUE=false
    ;;
  *)
    TEST_SUCCESS_VALUE="*new(${TYPE_INPUT})"
	TEST_FAIL_VALUE="*new(${TYPE_INPUT})"
    ;;
esac

# Go本体生成
cat <<EOF > $OUT_FILE
// Package ctxhelper is provides utilities for securely maintaining metadata
// during request processing for Echo and the standard context.Context.
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
)

type ${NAME_LOWER}KeyType struct{}

var ${NAME_LOWER}Key = ${NAME_LOWER}KeyType{}

func With${NAME_CAMEL}(ctx context.Context, val ${TYPE_INPUT}) context.Context {
	return context.WithValue(ctx, ${NAME_LOWER}Key, val)
}

func ${NAME_CAMEL}FromContext(ctx context.Context) (${TYPE_INPUT}, bool) {
	val := ctx.Value(${NAME_LOWER}Key)
	if v, ok := val.(${TYPE_INPUT}); ok {
		return v, true
	}
	return *new(${TYPE_INPUT}), false
}
EOF

cat <<EOF > $TEST_FILE
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestWith${NAME_CAMEL}(t *testing.T) {
	t.Parallel()

	base := context.Background()
	ctx := context.WithValue(base, ${NAME_LOWER}Key, ${TEST_SUCCESS_VALUE})

	val := ctx.Value(${NAME_LOWER}Key)
	require.NotNil(t, val)
	v, ok := val.(${TYPE_INPUT})
	require.True(t, ok)
	require.Equal(t, ${TEST_SUCCESS_VALUE}, v)
}

func Test${NAME_CAMEL}FromContext(t *testing.T) {
	t.Parallel()

	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = With${NAME_CAMEL}(ctx, ${TEST_SUCCESS_VALUE})

		val, ok := ${NAME_CAMEL}FromContext(ctx)
		require.True(t, ok)
		require.Equal(t, ${TEST_SUCCESS_VALUE}, val)
	})

	t.Run("standard context - no value", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := ${NAME_CAMEL}FromContext(ctx)
		require.False(t, ok)
		require.Equal(t, ${TEST_FAIL_VALUE}, val)
	})
}
EOF

echo "✅ ${OUT_FILE} を生成しました"
echo "✅ ${TEST_FILE} を生成しました"
if [[ "$TEST_SUCCESS_VALUE" =~ ^\*new\(([A-Za-z0-9_]+\.[A-Za-z0-9_]+)\)$ ]]; then
	echo "⚠️ プリミティブな型以外を検出しました。生成されたファイルで Ctrl + S（保存）して、自動インポートを実行してください。"
fi
