// Code generated by MockGen. DO NOT EDIT.
// Source: replay.go
//
// Generated by this command:
//
//	mockgen -source=replay.go -destination=mock/mock_replay.go.gen.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReplayUsecase is a mock of ReplayUsecase interface.
type MockReplayUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockReplayUsecaseMockRecorder
	isgomock struct{}
}

// MockReplayUsecaseMockRecorder is the mock recorder for MockReplayUsecase.
type MockReplayUsecaseMockRecorder struct {
	mock *MockReplayUsecase
}

// NewMockReplayUsecase creates a new mock instance.
func NewMockReplayUsecase(ctrl *gomock.Controller) *MockReplayUsecase {
	mock := &MockReplayUsecase{ctrl: ctrl}
	mock.recorder = &MockReplayUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayUsecase) EXPECT() *MockReplayUsecaseMockRecorder {
	return m.recorder
}

// ReplayDead mocks base method.
func (m *MockReplayUsecase) ReplayDead(ctx context.Context, messageID *uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayDead", ctx, messageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplayDead indicates an expected call of ReplayDead.
func (mr *MockReplayUsecaseMockRecorder) ReplayDead(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayDead", reflect.TypeOf((*MockReplayUsecase)(nil).ReplayDead), ctx, messageID)
}
