// Code generated by MockGen. DO NOT EDIT.
// Source: relay.go
//
// Generated by this command:
//
//	mockgen -source=relay.go -destination=mock/mock_relay.go.gen.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	outbox "go-boilerplate/internal/usecase/outbox"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncDead mocks base method.
func (m *MockMetrics) IncDead(ctx context.Context, channel string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncDead", ctx, channel)
}

// IncDead indicates an expected call of IncDead.
func (mr *MockMetricsMockRecorder) IncDead(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncDead", reflect.TypeOf((*MockMetrics)(nil).IncDead), ctx, channel)
}

// SetBlockedStreams mocks base method.
func (m *MockMetrics) SetBlockedStreams(ctx context.Context, channel string, count int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBlockedStreams", ctx, channel, count)
}

// SetBlockedStreams indicates an expected call of SetBlockedStreams.
func (mr *MockMetricsMockRecorder) SetBlockedStreams(ctx, channel, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedStreams", reflect.TypeOf((*MockMetrics)(nil).SetBlockedStreams), ctx, channel, count)
}

// SetLagSeconds mocks base method.
func (m *MockMetrics) SetLagSeconds(ctx context.Context, channel string, seconds int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLagSeconds", ctx, channel, seconds)
}

// SetLagSeconds indicates an expected call of SetLagSeconds.
func (mr *MockMetricsMockRecorder) SetLagSeconds(ctx, channel, seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLagSeconds", reflect.TypeOf((*MockMetrics)(nil).SetLagSeconds), ctx, channel, seconds)
}

// MockRelayUsecase is a mock of RelayUsecase interface.
type MockRelayUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRelayUsecaseMockRecorder
	isgomock struct{}
}

// MockRelayUsecaseMockRecorder is the mock recorder for MockRelayUsecase.
type MockRelayUsecaseMockRecorder struct {
	mock *MockRelayUsecase
}

// NewMockRelayUsecase creates a new mock instance.
func NewMockRelayUsecase(ctrl *gomock.Controller) *MockRelayUsecase {
	mock := &MockRelayUsecase{ctrl: ctrl}
	mock.recorder = &MockRelayUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayUsecase) EXPECT() *MockRelayUsecaseMockRecorder {
	return m.recorder
}

// RecordBlockedStreams mocks base method.
func (m *MockRelayUsecase) RecordBlockedStreams(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBlockedStreams", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordBlockedStreams indicates an expected call of RecordBlockedStreams.
func (mr *MockRelayUsecaseMockRecorder) RecordBlockedStreams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBlockedStreams", reflect.TypeOf((*MockRelayUsecase)(nil).RecordBlockedStreams), ctx)
}

// RecordLag mocks base method.
func (m *MockRelayUsecase) RecordLag(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLag", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLag indicates an expected call of RecordLag.
func (mr *MockRelayUsecaseMockRecorder) RecordLag(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLag", reflect.TypeOf((*MockRelayUsecase)(nil).RecordLag), ctx)
}

// RelayBatch mocks base method.
func (m *MockRelayUsecase) RelayBatch(ctx context.Context, batchSize int32) (outbox.RelayResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelayBatch", ctx, batchSize)
	ret0, _ := ret[0].(outbox.RelayResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelayBatch indicates an expected call of RelayBatch.
func (mr *MockRelayUsecaseMockRecorder) RelayBatch(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelayBatch", reflect.TypeOf((*MockRelayUsecase)(nil).RelayBatch), ctx, batchSize)
}
