// Code generated by MockGen. DO NOT EDIT.
// Source: emit.go
//
// Generated by this command:
//
//	mockgen -source=emit.go -destination=mock/mock_emit.gen.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	outbox "go-boilerplate/internal/usecase/outbox"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmitUsecase is a mock of EmitUsecase interface.
type MockEmitUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockEmitUsecaseMockRecorder
	isgomock struct{}
}

// MockEmitUsecaseMockRecorder is the mock recorder for MockEmitUsecase.
type MockEmitUsecaseMockRecorder struct {
	mock *MockEmitUsecase
}

// NewMockEmitUsecase creates a new mock instance.
func NewMockEmitUsecase(ctrl *gomock.Controller) *MockEmitUsecase {
	mock := &MockEmitUsecase{ctrl: ctrl}
	mock.recorder = &MockEmitUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitUsecase) EXPECT() *MockEmitUsecaseMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitUsecase) Emit(ctx context.Context, in outbox.EmitInput) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", ctx, in)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitUsecaseMockRecorder) Emit(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitUsecase)(nil).Emit), ctx, in)
}
