// Code generated by MockGen. DO NOT EDIT.
// Source: relay.go
//
// Generated by this command:
//
//	mockgen -source=relay.go -destination=mock/mock_relay.gen.go -package=mock_outbox
//

// Package mock_outbox is a generated GoMock package.
package mock_outbox

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRelayUsecase is a mock of RelayUsecase interface.
type MockRelayUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRelayUsecaseMockRecorder
	isgomock struct{}
}

// MockRelayUsecaseMockRecorder is the mock recorder for MockRelayUsecase.
type MockRelayUsecaseMockRecorder struct {
	mock *MockRelayUsecase
}

// NewMockRelayUsecase creates a new mock instance.
func NewMockRelayUsecase(ctrl *gomock.Controller) *MockRelayUsecase {
	mock := &MockRelayUsecase{ctrl: ctrl}
	mock.recorder = &MockRelayUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayUsecase) EXPECT() *MockRelayUsecaseMockRecorder {
	return m.recorder
}

// RecordLag mocks base method.
func (m *MockRelayUsecase) RecordLag(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordLag", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordLag indicates an expected call of RecordLag.
func (mr *MockRelayUsecaseMockRecorder) RecordLag(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLag", reflect.TypeOf((*MockRelayUsecase)(nil).RecordLag), ctx)
}

// RelayBatch mocks base method.
func (m *MockRelayUsecase) RelayBatch(ctx context.Context, batchSize int32) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelayBatch", ctx, batchSize)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelayBatch indicates an expected call of RelayBatch.
func (mr *MockRelayUsecaseMockRecorder) RelayBatch(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelayBatch", reflect.TypeOf((*MockRelayUsecase)(nil).RelayBatch), ctx, batchSize)
}
