// Code generated by MockGen. DO NOT EDIT.
// Source: user_search_usecase.go
//
// Generated by this command:
//
//	mockgen -source=user_search_usecase.go -destination=mock/mock_user_search_usecase.gen.go -package=mock_search
//

// Package mock_search is a generated GoMock package.
package mock_search

import (
	context "context"
	paging "go-boilerplate/internal/usecase/tools/paging"
	search "go-boilerplate/internal/usecase/user/search"
	query "go-boilerplate/internal/usecase/user/search/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CountUsersByKeyword mocks base method.
func (m *MockUsecase) CountUsersByKeyword(ctx context.Context, filter *search.SearchParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByKeyword", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByKeyword indicates an expected call of CountUsersByKeyword.
func (mr *MockUsecaseMockRecorder) CountUsersByKeyword(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByKeyword", reflect.TypeOf((*MockUsecase)(nil).CountUsersByKeyword), ctx, filter)
}

// ListUsersByKeyword mocks base method.
func (m *MockUsecase) ListUsersByKeyword(ctx context.Context, filter *search.SearchParams, page *paging.Page) (query.UserSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByKeyword", ctx, filter, page)
	ret0, _ := ret[0].(query.UserSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByKeyword indicates an expected call of ListUsersByKeyword.
func (mr *MockUsecaseMockRecorder) ListUsersByKeyword(ctx, filter, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByKeyword", reflect.TypeOf((*MockUsecase)(nil).ListUsersByKeyword), ctx, filter, page)
}

// ListUsersByKeywordWithTotal mocks base method.
func (m *MockUsecase) ListUsersByKeywordWithTotal(ctx context.Context, filter *search.SearchParams, page *paging.Page) (*search.UserSearchListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByKeywordWithTotal", ctx, filter, page)
	ret0, _ := ret[0].(*search.UserSearchListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByKeywordWithTotal indicates an expected call of ListUsersByKeywordWithTotal.
func (mr *MockUsecaseMockRecorder) ListUsersByKeywordWithTotal(ctx, filter, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByKeywordWithTotal", reflect.TypeOf((*MockUsecase)(nil).ListUsersByKeywordWithTotal), ctx, filter, page)
}
