// Code generated by MockGen. DO NOT EDIT.
// Source: exchangerate_usecase.go
//
// Generated by this command:
//
//	mockgen -source=exchangerate_usecase.go -destination=mock/mock_exchangerate_usecase.go.gen.go -package=mock_exchangerate
//

// Package mock_exchangerate is a generated GoMock package.
package mock_exchangerate

import (
	context "context"
	exchangerate "go-boilerplate/internal/usecase/exchangerate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockUsecase) Convert(ctx context.Context, in exchangerate.ConvertInput) (*exchangerate.ConvertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", ctx, in)
	ret0, _ := ret[0].(*exchangerate.ConvertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockUsecaseMockRecorder) Convert(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockUsecase)(nil).Convert), ctx, in)
}
