// Code generated by MockGen. DO NOT EDIT.
// Source: inquiry_usecase.go
//
// Generated by this command:
//
//	mockgen -source=inquiry_usecase.go -destination=mock/mock_inquiry_usecase.go.gen.go -package=mock_inquiry
//

// Package mock_inquiry is a generated GoMock package.
package mock_inquiry

import (
	context "context"
	auth "go-boilerplate/internal/usecase/boundary/auth"
	inquiry "go-boilerplate/internal/usecase/inquiry"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AppendMessage mocks base method.
func (m *MockUsecase) AppendMessage(ctx context.Context, params inquiry.AppendMessageParams) (inquiry.MessageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendMessage", ctx, params)
	ret0, _ := ret[0].(inquiry.MessageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendMessage indicates an expected call of AppendMessage.
func (mr *MockUsecaseMockRecorder) AppendMessage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendMessage", reflect.TypeOf((*MockUsecase)(nil).AppendMessage), ctx, params)
}

// GetHistory mocks base method.
func (m *MockUsecase) GetHistory(ctx context.Context, params inquiry.HistoryParams) (*inquiry.HistoryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, params)
	ret0, _ := ret[0].(*inquiry.HistoryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockUsecaseMockRecorder) GetHistory(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockUsecase)(nil).GetHistory), ctx, params)
}

// GetInquiryHistory mocks base method.
func (m *MockUsecase) GetInquiryHistory(ctx context.Context, authn *auth.Authn, params inquiry.OperatorHistoryParams) (*inquiry.HistoryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInquiryHistory", ctx, authn, params)
	ret0, _ := ret[0].(*inquiry.HistoryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInquiryHistory indicates an expected call of GetInquiryHistory.
func (mr *MockUsecaseMockRecorder) GetInquiryHistory(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInquiryHistory", reflect.TypeOf((*MockUsecase)(nil).GetInquiryHistory), ctx, authn, params)
}

// IssueFeedTicket mocks base method.
func (m *MockUsecase) IssueFeedTicket(ctx context.Context, authn *auth.Authn) (inquiry.TicketView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueFeedTicket", ctx, authn)
	ret0, _ := ret[0].(inquiry.TicketView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueFeedTicket indicates an expected call of IssueFeedTicket.
func (mr *MockUsecaseMockRecorder) IssueFeedTicket(ctx, authn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueFeedTicket", reflect.TypeOf((*MockUsecase)(nil).IssueFeedTicket), ctx, authn)
}

// IssueStreamTicket mocks base method.
func (m *MockUsecase) IssueStreamTicket(ctx context.Context, params inquiry.IssueStreamTicketParams) (inquiry.TicketView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueStreamTicket", ctx, params)
	ret0, _ := ret[0].(inquiry.TicketView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueStreamTicket indicates an expected call of IssueStreamTicket.
func (mr *MockUsecaseMockRecorder) IssueStreamTicket(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueStreamTicket", reflect.TypeOf((*MockUsecase)(nil).IssueStreamTicket), ctx, params)
}

// ListInquiries mocks base method.
func (m *MockUsecase) ListInquiries(ctx context.Context, authn *auth.Authn, params inquiry.ListInquiriesParams) (*inquiry.InquiryListView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInquiries", ctx, authn, params)
	ret0, _ := ret[0].(*inquiry.InquiryListView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInquiries indicates an expected call of ListInquiries.
func (mr *MockUsecaseMockRecorder) ListInquiries(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInquiries", reflect.TypeOf((*MockUsecase)(nil).ListInquiries), ctx, authn, params)
}

// Reply mocks base method.
func (m *MockUsecase) Reply(ctx context.Context, authn *auth.Authn, params inquiry.ReplyParams) (inquiry.MessageView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reply", ctx, authn, params)
	ret0, _ := ret[0].(inquiry.MessageView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockUsecaseMockRecorder) Reply(ctx, authn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockUsecase)(nil).Reply), ctx, authn, params)
}
