// Code generated by MockGen. DO NOT EDIT.
// Source: status_usecase.go
//
// Generated by this command:
//
//	mockgen -source=status_usecase.go -destination=mock/mock_status_usecase.go.gen.go -package=mock_status
//

// Package mock_status is a generated GoMock package.
package mock_status

import (
	context "context"
	status "go-boilerplate/internal/usecase/product/status"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ListStatuses mocks base method.
func (m *MockUsecase) ListStatuses(ctx context.Context) (status.StatusDTOs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStatuses", ctx)
	ret0, _ := ret[0].(status.StatusDTOs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStatuses indicates an expected call of ListStatuses.
func (mr *MockUsecaseMockRecorder) ListStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStatuses", reflect.TypeOf((*MockUsecase)(nil).ListStatuses), ctx)
}
