// Code generated by MockGen. DO NOT EDIT.
// Source: exchangerate.go
//
// Generated by this command:
//
//	mockgen -source=exchangerate.go -destination=mock/mock_exchangerate.gen.go -package=mock_exchangerate
//

// Package mock_exchangerate is a generated GoMock package.
package mock_exchangerate

import (
	context "context"
	exchangerate "go-boilerplate/internal/usecase/boundary/exchangerate"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockGateway) GetRate(ctx context.Context, base, quote string) (*exchangerate.Rate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, base, quote)
	ret0, _ := ret[0].(*exchangerate.Rate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRate indicates an expected call of GetRate.
func (mr *MockGatewayMockRecorder) GetRate(ctx, base, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockGateway)(nil).GetRate), ctx, base, quote)
}
