// Code generated by MockGen. DO NOT EDIT.
// Source: product_repository.go
//
// Generated by this command:
//
//	mockgen -source=product_repository.go -destination=mock/mock_product_repository.go.gen.go -package=mock_product
//

// Package mock_product is a generated GoMock package.
package mock_product

import (
	context "context"
	product "go-boilerplate/internal/domain/product"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindPublishedList mocks base method.
func (m *MockRepository) FindPublishedList(ctx context.Context, params product.ListParams) (product.Products, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublishedList", ctx, params)
	ret0, _ := ret[0].(product.Products)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublishedList indicates an expected call of FindPublishedList.
func (mr *MockRepositoryMockRecorder) FindPublishedList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublishedList", reflect.TypeOf((*MockRepository)(nil).FindPublishedList), ctx, params)
}
