// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mock/mock_admin.go.gen.go -package=mock_dbslot
//

// Package mock_dbslot is a generated GoMock package.
package mock_dbslot

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBAdmin is a mock of DBAdmin interface.
type MockDBAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockDBAdminMockRecorder
	isgomock struct{}
}

// MockDBAdminMockRecorder is the mock recorder for MockDBAdmin.
type MockDBAdminMockRecorder struct {
	mock *MockDBAdmin
}

// NewMockDBAdmin creates a new mock instance.
func NewMockDBAdmin(ctrl *gomock.Controller) *MockDBAdmin {
	mock := &MockDBAdmin{ctrl: ctrl}
	mock.recorder = &MockDBAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBAdmin) EXPECT() *MockDBAdminMockRecorder {
	return m.recorder
}

// ActiveConnections mocks base method.
func (m *MockDBAdmin) ActiveConnections(ctx context.Context, names ...string) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range names {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ActiveConnections", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveConnections indicates an expected call of ActiveConnections.
func (mr *MockDBAdminMockRecorder) ActiveConnections(ctx any, names ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, names...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveConnections", reflect.TypeOf((*MockDBAdmin)(nil).ActiveConnections), varargs...)
}

// EnsureDatabase mocks base method.
func (m *MockDBAdmin) EnsureDatabase(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDatabase", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDatabase indicates an expected call of EnsureDatabase.
func (mr *MockDBAdminMockRecorder) EnsureDatabase(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDatabase", reflect.TypeOf((*MockDBAdmin)(nil).EnsureDatabase), ctx, name)
}

// SetupDatabase mocks base method.
func (m *MockDBAdmin) SetupDatabase(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupDatabase", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupDatabase indicates an expected call of SetupDatabase.
func (mr *MockDBAdminMockRecorder) SetupDatabase(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupDatabase", reflect.TypeOf((*MockDBAdmin)(nil).SetupDatabase), ctx, name)
}
