// Code generated by MockGen. DO NOT EDIT.
// Source: compose.go
//
// Generated by this command:
//
//	mockgen -source=compose.go -destination=mock/mock_compose.go.gen.go -package=mock_dbslot
//

// Package mock_dbslot is a generated GoMock package.
package mock_dbslot

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompose is a mock of Compose interface.
type MockCompose struct {
	ctrl     *gomock.Controller
	recorder *MockComposeMockRecorder
	isgomock struct{}
}

// MockComposeMockRecorder is the mock recorder for MockCompose.
type MockComposeMockRecorder struct {
	mock *MockCompose
}

// NewMockCompose creates a new mock instance.
func NewMockCompose(ctrl *gomock.Controller) *MockCompose {
	mock := &MockCompose{ctrl: ctrl}
	mock.recorder = &MockComposeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompose) EXPECT() *MockComposeMockRecorder {
	return m.recorder
}

// DownServe mocks base method.
func (m *MockCompose) DownServe(ctx context.Context, project string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownServe", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownServe indicates an expected call of DownServe.
func (mr *MockComposeMockRecorder) DownServe(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownServe", reflect.TypeOf((*MockCompose)(nil).DownServe), ctx, project)
}

// UpSharedDB mocks base method.
func (m *MockCompose) UpSharedDB(ctx context.Context, project string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpSharedDB", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpSharedDB indicates an expected call of UpSharedDB.
func (mr *MockComposeMockRecorder) UpSharedDB(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpSharedDB", reflect.TypeOf((*MockCompose)(nil).UpSharedDB), ctx, project)
}
