// Code generated by MockGen. DO NOT EDIT.
// Source: objectstorage.go
//
// Generated by this command:
//
//	mockgen -source=objectstorage.go -destination=mock/mock_objectstorage.go.gen.go -package=mock_objectstorage
//

// Package mock_objectstorage is a generated GoMock package.
package mock_objectstorage

import (
	context "context"
	objectstorage "go-boilerplate/internal/usecase/boundary/objectstorage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockStorage) Put(ctx context.Context, obj objectstorage.PutObject) (objectstorage.Path, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, obj)
	ret0, _ := ret[0].(objectstorage.Path)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockStorageMockRecorder) Put(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStorage)(nil).Put), ctx, obj)
}
