// Code generated by MockGen. DO NOT EDIT.
// Source: coupon_repository.go
//
// Generated by this command:
//
//	mockgen -source=coupon_repository.go -destination=mock/mock_coupon_repository.go.gen.go -package=mock_coupon
//

// Package mock_coupon is a generated GoMock package.
package mock_coupon

import (
	context "context"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountByScopeTargetProductID mocks base method.
func (m *MockRepository) CountByScopeTargetProductID(ctx context.Context, productID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByScopeTargetProductID", ctx, productID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByScopeTargetProductID indicates an expected call of CountByScopeTargetProductID.
func (mr *MockRepositoryMockRecorder) CountByScopeTargetProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByScopeTargetProductID", reflect.TypeOf((*MockRepository)(nil).CountByScopeTargetProductID), ctx, productID)
}
