// Code generated by MockGen. DO NOT EDIT.
// Source: coupon_repository.go
//
// Generated by this command:
//
//	mockgen -source=coupon_repository.go -destination=mock/mock_coupon_repository.go.gen.go -package=mock_coupon
//

// Package mock_coupon is a generated GoMock package.
package mock_coupon

import (
	context "context"
	coupon "go-boilerplate/internal/domain/coupon"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (coupon.Coupons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(coupon.Coupons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockRepository)(nil).FindByUserID), ctx, userID)
}

// LockByID mocks base method.
func (m *MockRepository) LockByID(ctx context.Context, id uuid.UUID) (*coupon.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByID", ctx, id)
	ret0, _ := ret[0].(*coupon.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockByID indicates an expected call of LockByID.
func (mr *MockRepositoryMockRecorder) LockByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByID", reflect.TypeOf((*MockRepository)(nil).LockByID), ctx, id)
}

// UpdateUsed mocks base method.
func (m *MockRepository) UpdateUsed(ctx context.Context, id uuid.UUID, usedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsed", ctx, id, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsed indicates an expected call of UpdateUsed.
func (mr *MockRepositoryMockRecorder) UpdateUsed(ctx, id, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsed", reflect.TypeOf((*MockRepository)(nil).UpdateUsed), ctx, id, usedAt)
}
