// Code generated by MockGen. DO NOT EDIT.
// Source: product_ranking_usecase.go
//
// Generated by this command:
//
//	mockgen -source=product_ranking_usecase.go -destination=mock/mock_product_ranking_usecase.go.gen.go -package=mock_ranking
//

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	context "context"
	ranking "go-boilerplate/internal/usecase/product/ranking"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetProductsRanking mocks base method.
func (m *MockUsecase) GetProductsRanking(ctx context.Context, params ranking.GetRankingParams) (ranking.RankingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsRanking", ctx, params)
	ret0, _ := ret[0].(ranking.RankingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsRanking indicates an expected call of GetProductsRanking.
func (mr *MockUsecaseMockRecorder) GetProductsRanking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsRanking", reflect.TypeOf((*MockUsecase)(nil).GetProductsRanking), ctx, params)
}
