// Code generated by MockGen. DO NOT EDIT.
// Source: product_ranking_usecase.go
//
// Generated by this command:
//
//	mockgen -source=product_ranking_usecase.go -destination=mock/mock_product_ranking_usecase.go.gen.go -package=mock_ranking
//

// Package mock_ranking is a generated GoMock package.
package mock_ranking

import (
	context "context"
	ranking "go-boilerplate/internal/usecase/product/ranking"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetAmountRanking mocks base method.
func (m *MockUsecase) GetAmountRanking(ctx context.Context, params ranking.GetRankingParams) (ranking.AmountRankingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmountRanking", ctx, params)
	ret0, _ := ret[0].(ranking.AmountRankingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmountRanking indicates an expected call of GetAmountRanking.
func (mr *MockUsecaseMockRecorder) GetAmountRanking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmountRanking", reflect.TypeOf((*MockUsecase)(nil).GetAmountRanking), ctx, params)
}

// GetQuantityRanking mocks base method.
func (m *MockUsecase) GetQuantityRanking(ctx context.Context, params ranking.GetRankingParams) (ranking.QuantityRankingView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuantityRanking", ctx, params)
	ret0, _ := ret[0].(ranking.QuantityRankingView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuantityRanking indicates an expected call of GetQuantityRanking.
func (mr *MockUsecaseMockRecorder) GetQuantityRanking(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuantityRanking", reflect.TypeOf((*MockUsecase)(nil).GetQuantityRanking), ctx, params)
}
