// Code generated by MockGen. DO NOT EDIT.
// Source: user_search_usecase_query_service.go
//
// Generated by this command:
//
//	mockgen -source=user_search_usecase_query_service.go -destination=mock/mock_user_search_usecase_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/user/search/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserSearchQueryService is a mock of UserSearchQueryService interface.
type MockUserSearchQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockUserSearchQueryServiceMockRecorder
	isgomock struct{}
}

// MockUserSearchQueryServiceMockRecorder is the mock recorder for MockUserSearchQueryService.
type MockUserSearchQueryServiceMockRecorder struct {
	mock *MockUserSearchQueryService
}

// NewMockUserSearchQueryService creates a new mock instance.
func NewMockUserSearchQueryService(ctrl *gomock.Controller) *MockUserSearchQueryService {
	mock := &MockUserSearchQueryService{ctrl: ctrl}
	mock.recorder = &MockUserSearchQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSearchQueryService) EXPECT() *MockUserSearchQueryServiceMockRecorder {
	return m.recorder
}

// CountByFilter mocks base method.
func (m *MockUserSearchQueryService) CountByFilter(ctx context.Context, filter *query.UserSearchFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByFilter", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByFilter indicates an expected call of CountByFilter.
func (mr *MockUserSearchQueryServiceMockRecorder) CountByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByFilter", reflect.TypeOf((*MockUserSearchQueryService)(nil).CountByFilter), ctx, filter)
}

// FindByFilter mocks base method.
func (m *MockUserSearchQueryService) FindByFilter(ctx context.Context, filter *query.UserSearchFilter, limit, offset int32) (query.UserSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter, limit, offset)
	ret0, _ := ret[0].(query.UserSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockUserSearchQueryServiceMockRecorder) FindByFilter(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockUserSearchQueryService)(nil).FindByFilter), ctx, filter, limit, offset)
}
