// Code generated by MockGen. DO NOT EDIT.
// Source: user_search_usecase_query_service.go
//
// Generated by this command:
//
//	mockgen -source=user_search_usecase_query_service.go -destination=mock/mock_user_search_usecase_query_service.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	query "boilerplate-go/internal/usecase/user/search/query"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserQueryService is a mock of UserQueryService interface.
type MockUserQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueryServiceMockRecorder
	isgomock struct{}
}

// MockUserQueryServiceMockRecorder is the mock recorder for MockUserQueryService.
type MockUserQueryServiceMockRecorder struct {
	mock *MockUserQueryService
}

// NewMockUserQueryService creates a new mock instance.
func NewMockUserQueryService(ctrl *gomock.Controller) *MockUserQueryService {
	mock := &MockUserQueryService{ctrl: ctrl}
	mock.recorder = &MockUserQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueryService) EXPECT() *MockUserQueryServiceMockRecorder {
	return m.recorder
}

// CountByFilter mocks base method.
func (m *MockUserQueryService) CountByFilter(ctx context.Context, filter *query.UserSearchFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByFilter", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByFilter indicates an expected call of CountByFilter.
func (mr *MockUserQueryServiceMockRecorder) CountByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByFilter", reflect.TypeOf((*MockUserQueryService)(nil).CountByFilter), ctx, filter)
}

// FindByFilter mocks base method.
func (m *MockUserQueryService) FindByFilter(ctx context.Context, filter *query.UserSearchFilter, limit, offset int32) (query.UserSearchResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter, limit, offset)
	ret0, _ := ret[0].(query.UserSearchResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockUserQueryServiceMockRecorder) FindByFilter(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockUserQueryService)(nil).FindByFilter), ctx, filter, limit, offset)
}
