// Code generated by MockGen. DO NOT EDIT.
// Source: field_builder.go
//
// Generated by this command:
//
//	mockgen -source=field_builder.go -destination=mock/mock_field_builder.go -package=mock_logging
//

// Package mock_logging is a generated GoMock package.
package mock_logging

import (
	logging "boilerplate-go/internal/logging"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogFieldBuilder is a mock of LogFieldBuilder interface.
type MockLogFieldBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockLogFieldBuilderMockRecorder
	isgomock struct{}
}

// MockLogFieldBuilderMockRecorder is the mock recorder for MockLogFieldBuilder.
type MockLogFieldBuilderMockRecorder struct {
	mock *MockLogFieldBuilder
}

// NewMockLogFieldBuilder creates a new mock instance.
func NewMockLogFieldBuilder(ctrl *gomock.Controller) *MockLogFieldBuilder {
	mock := &MockLogFieldBuilder{ctrl: ctrl}
	mock.recorder = &MockLogFieldBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogFieldBuilder) EXPECT() *MockLogFieldBuilderMockRecorder {
	return m.recorder
}

// BuildHTTPRequestFields mocks base method.
func (m *MockLogFieldBuilder) BuildHTTPRequestFields(req logging.HTTPRequestLogInput) []*logging.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildHTTPRequestFields", req)
	ret0, _ := ret[0].([]*logging.Field)
	return ret0
}

// BuildHTTPRequestFields indicates an expected call of BuildHTTPRequestFields.
func (mr *MockLogFieldBuilderMockRecorder) BuildHTTPRequestFields(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildHTTPRequestFields", reflect.TypeOf((*MockLogFieldBuilder)(nil).BuildHTTPRequestFields), req)
}

// BuildHTTPResponseFields mocks base method.
func (m *MockLogFieldBuilder) BuildHTTPResponseFields(resp logging.HTTPResponseLogInput) []*logging.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildHTTPResponseFields", resp)
	ret0, _ := ret[0].([]*logging.Field)
	return ret0
}

// BuildHTTPResponseFields indicates an expected call of BuildHTTPResponseFields.
func (mr *MockLogFieldBuilderMockRecorder) BuildHTTPResponseFields(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildHTTPResponseFields", reflect.TypeOf((*MockLogFieldBuilder)(nil).BuildHTTPResponseFields), resp)
}

// BuildObservabilityFields mocks base method.
func (m *MockLogFieldBuilder) BuildObservabilityFields(obs logging.ObservabilityFieldsInput) []*logging.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildObservabilityFields", obs)
	ret0, _ := ret[0].([]*logging.Field)
	return ret0
}

// BuildObservabilityFields indicates an expected call of BuildObservabilityFields.
func (mr *MockLogFieldBuilderMockRecorder) BuildObservabilityFields(obs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildObservabilityFields", reflect.TypeOf((*MockLogFieldBuilder)(nil).BuildObservabilityFields), obs)
}

// BuildSQLFields mocks base method.
func (m *MockLogFieldBuilder) BuildSQLFields(sql logging.SQLFieldsInput) []*logging.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSQLFields", sql)
	ret0, _ := ret[0].([]*logging.Field)
	return ret0
}

// BuildSQLFields indicates an expected call of BuildSQLFields.
func (mr *MockLogFieldBuilderMockRecorder) BuildSQLFields(sql any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSQLFields", reflect.TypeOf((*MockLogFieldBuilder)(nil).BuildSQLFields), sql)
}
