// Code generated by MockGen. DO NOT EDIT.
// Source: product_image_query_service.go
//
// Generated by this command:
//
//	mockgen -source=product_image_query_service.go -destination=mock/mock_product_image_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductImageQueryService is a mock of ProductImageQueryService interface.
type MockProductImageQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockProductImageQueryServiceMockRecorder
	isgomock struct{}
}

// MockProductImageQueryServiceMockRecorder is the mock recorder for MockProductImageQueryService.
type MockProductImageQueryServiceMockRecorder struct {
	mock *MockProductImageQueryService
}

// NewMockProductImageQueryService creates a new mock instance.
func NewMockProductImageQueryService(ctrl *gomock.Controller) *MockProductImageQueryService {
	mock := &MockProductImageQueryService{ctrl: ctrl}
	mock.recorder = &MockProductImageQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductImageQueryService) EXPECT() *MockProductImageQueryServiceMockRecorder {
	return m.recorder
}

// FilterExistingImagePaths mocks base method.
func (m *MockProductImageQueryService) FilterExistingImagePaths(ctx context.Context, paths []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterExistingImagePaths", ctx, paths)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterExistingImagePaths indicates an expected call of FilterExistingImagePaths.
func (mr *MockProductImageQueryServiceMockRecorder) FilterExistingImagePaths(ctx, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterExistingImagePaths", reflect.TypeOf((*MockProductImageQueryService)(nil).FilterExistingImagePaths), ctx, paths)
}
