// Code generated by MockGen. DO NOT EDIT.
// Source: discontinue_impact_query_service.go
//
// Generated by this command:
//
//	mockgen -source=discontinue_impact_query_service.go -destination=mock/mock_discontinue_impact_query_service.go.gen.go -package=mock_query
//

// Package mock_query is a generated GoMock package.
package mock_query

import (
	context "context"
	query "go-boilerplate/internal/usecase/product/query"
	uuid "go-boilerplate/pkg/uuid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscontinueImpactQueryService is a mock of DiscontinueImpactQueryService interface.
type MockDiscontinueImpactQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockDiscontinueImpactQueryServiceMockRecorder
	isgomock struct{}
}

// MockDiscontinueImpactQueryServiceMockRecorder is the mock recorder for MockDiscontinueImpactQueryService.
type MockDiscontinueImpactQueryServiceMockRecorder struct {
	mock *MockDiscontinueImpactQueryService
}

// NewMockDiscontinueImpactQueryService creates a new mock instance.
func NewMockDiscontinueImpactQueryService(ctrl *gomock.Controller) *MockDiscontinueImpactQueryService {
	mock := &MockDiscontinueImpactQueryService{ctrl: ctrl}
	mock.recorder = &MockDiscontinueImpactQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscontinueImpactQueryService) EXPECT() *MockDiscontinueImpactQueryServiceMockRecorder {
	return m.recorder
}

// EstimateDiscontinueImpact mocks base method.
func (m *MockDiscontinueImpactQueryService) EstimateDiscontinueImpact(ctx context.Context, productID uuid.UUID) (query.DiscontinueImpactReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateDiscontinueImpact", ctx, productID)
	ret0, _ := ret[0].(query.DiscontinueImpactReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateDiscontinueImpact indicates an expected call of EstimateDiscontinueImpact.
func (mr *MockDiscontinueImpactQueryServiceMockRecorder) EstimateDiscontinueImpact(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateDiscontinueImpact", reflect.TypeOf((*MockDiscontinueImpactQueryService)(nil).EstimateDiscontinueImpact), ctx, productID)
}
