// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	auth "go-boilerplate/internal/usecase/boundary/auth"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
)

func TestSetAuthn(t *testing.T) {
	t.Parallel()

	base := context.Background()
	ctx := context.WithValue(base, authnKey, *new(auth.Authn))

	val := ctx.Value(authnKey)
	v, ok := val.(auth.Authn)
	assert.True(t, ok)
	assert.Equal(t, *new(auth.Authn), v)
}

func TestGetAuthn(t *testing.T) {
	t.Parallel()

	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = SetAuthn(ctx, *new(auth.Authn))

		val, ok := GetAuthn(ctx)
		assert.True(t, ok)
		assert.Equal(t, *new(auth.Authn), val)
	})

	t.Run("standard context - no value", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := GetAuthn(ctx)
		assert.False(t, ok)
		assert.Equal(t, *new(auth.Authn), val)
	})
}

func TestSetAuthnToEcho(t *testing.T) {
	t.Parallel()

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		SetAuthnToEcho(c, *new(auth.Authn))
		val, ok := GetAuthnFromEcho(c)

		assert.True(t, ok)
		assert.Equal(t, *new(auth.Authn), val)
	})

	t.Run("echo context - no value", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		val, ok := GetAuthnFromEcho(c)
		assert.False(t, ok)
		assert.Equal(t, *new(auth.Authn), val)
	})
}
