// Package ctxhelper is provides utilities for securely maintaining metadata
// during request processing for Echo and the standard context.Context.
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"

	"boilerplate-go/internal/usecase/boundary/auth"
)

type authnKeyType struct{}

var authnKey = authnKeyType{}

// --- std lib context ---

func SetAuthn(ctx context.Context, val auth.Authn) context.Context {
	return context.WithValue(ctx, authnKey, val)
}

func GetAuthn(ctx context.Context) (auth.Authn, bool) {
	val := ctx.Value(authnKey)
	if v, ok := val.(auth.Authn); ok {
		return v, true
	}
	return *new(auth.Authn), false
}
