// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"

	auth "boilerplate-go/internal/usecase/boundary/auth"

	"github.com/labstack/echo/v4"
)

type authnKeyType struct{}

var authnKey = authnKeyType{}

// --- std lib context ---

func SetAuthn(ctx context.Context, val auth.Authn) context.Context {
	return context.WithValue(ctx, authnKey, val)
}

func GetAuthn(ctx context.Context) (auth.Authn, bool) {
	val := ctx.Value(authnKey)
	if v, ok := val.(auth.Authn); ok {
		return v, true
	}
	return *new(auth.Authn), false
}

// --- echo.Context wrapper ---

func SetAuthnToEcho(c echo.Context, val auth.Authn) {
	ctx := context.WithValue(c.Request().Context(), authnKey, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetAuthnFromEcho(c echo.Context) (auth.Authn, bool) {
	val := c.Request().Context().Value(authnKey)
	if v, ok := val.(auth.Authn); ok {
		return v, true
	}
	return *new(auth.Authn), false
}
