// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/require"
)

func TestSetEchoContext(t *testing.T) {
	t.Parallel()

	base := context.Background()
	e := echo.New()
	req := httptest.NewRequestWithContext(base, http.MethodGet, "/", nil)
	rec := httptest.NewRecorder()
	c := e.NewContext(req, rec)

	ctx := SetEchoContext(base, c)

	val := ctx.Value(echocontextKey)
	require.NotNil(t, val)
	v, ok := val.(echo.Context)
	require.True(t, ok)
	require.Equal(t, c, v)
}

func TestGetEchoContext(t *testing.T) {
	t.Parallel()

	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		e := echo.New()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		ctx = SetEchoContext(ctx, c)

		val, ok := GetEchoContext(ctx)
		require.True(t, ok)
		require.Equal(t, c, val)
	})

	t.Run("standard context - no value", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		val, ok := GetEchoContext(ctx)
		require.False(t, ok)
		require.Equal(t, *new(echo.Context), val)
	})
}

func TestSetEchoContextToEcho(t *testing.T) {
	t.Parallel()

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		e2 := echo.New()
		req2 := httptest.NewRequestWithContext(ctx, http.MethodGet, "/other", nil)
		rec2 := httptest.NewRecorder()
		c2 := e2.NewContext(req2, rec2)

		SetEchoContextToEcho(c, c2)
		val, ok := GetEchoContextFromEcho(c)

		require.True(t, ok)
		require.Equal(t, c2, val)
	})

	t.Run("echo context - no value", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		ctx := context.Background()
		req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		val, ok := GetEchoContextFromEcho(c)
		require.False(t, ok)
		require.Equal(t, *new(echo.Context), val)
	})
}
