// Code generated by gen_ctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"

	"github.com/labstack/echo/v4"
)

type echocontextKeyType struct{}

var echocontextKey = echocontextKeyType{}

// --- std lib context ---

func SetEchoContext(ctx context.Context, val echo.Context) context.Context {
	return context.WithValue(ctx, echocontextKey, val)
}

func GetEchoContext(ctx context.Context) (echo.Context, bool) {
	val := ctx.Value(echocontextKey)
	if v, ok := val.(echo.Context); ok {
		return v, true
	}
	return *new(echo.Context), false
}

// --- echo.Context wrapper ---

func SetEchoContextToEcho(c echo.Context, val echo.Context) {
	ctx := context.WithValue(c.Request().Context(), echocontextKey, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetEchoContextFromEcho(c echo.Context) (echo.Context, bool) {
	val := c.Request().Context().Value(echocontextKey)
	if v, ok := val.(echo.Context); ok {
		return v, true
	}
	return *new(echo.Context), false
}
