// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"

	"github.com/labstack/echo/v5"
)

type errorhandledKeyType struct{}

var errorhandledKey = errorhandledKeyType{}

// --- std lib context ---

func SetErrorHandled(ctx context.Context, val bool) context.Context {
	return context.WithValue(ctx, errorhandledKey, val)
}

func GetErrorHandled(ctx context.Context) (bool, bool) {
	val := ctx.Value(errorhandledKey)
	if v, ok := val.(bool); ok {
		return v, true
	}
	var zero bool
	return zero, false
}

// --- echo.Context wrapper ---

func SetErrorHandledToEcho(c *echo.Context, val bool) {
	ctx := SetErrorHandled(c.Request().Context(), val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetErrorHandledFromEcho(c *echo.Context) (bool, bool) {
	return GetErrorHandled(c.Request().Context())
}
