// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSetErrorHandled(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("privateキーへ値を書き込む", func(t *testing.T) {
			t.Parallel()
			ctx := SetErrorHandled(context.Background(), true)

			v, ok := ctx.Value(errorhandledKey).(bool)
			require.True(t, ok)
			assert.Equal(t, true, v)
		})
	})
}

func TestGetErrorHandled(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("標準コンテキストから取得できる", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			ctx = SetErrorHandled(ctx, true)

			val, ok := GetErrorHandled(ctx)
			assert.True(t, ok)
			assert.Equal(t, true, val)
		})

		t.Run("ゼロ値を設定した場合も未設定と区別してokがtrueになる", func(t *testing.T) {
			t.Parallel()
			ctx := SetErrorHandled(context.Background(), false)

			val, ok := GetErrorHandled(ctx)
			assert.True(t, ok)
			assert.Equal(t, false, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			val, ok := GetErrorHandled(ctx)
			assert.False(t, ok)
			assert.Equal(t, false, val)
		})
	})
}

func TestSetErrorHandledToEcho(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoへ設定し取得できる", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			SetErrorHandledToEcho(c, true)
			val, ok := GetErrorHandledFromEcho(c)

			assert.True(t, ok)
			assert.Equal(t, true, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoに値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			val, ok := GetErrorHandledFromEcho(c)
			assert.False(t, ok)
			assert.Equal(t, false, val)
		})
	})
}
