// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
)

func TestSetErrorHandled(t *testing.T) {
	t.Parallel()

	// SetErrorHandled が private な errorhandledKey で値を書き込むことを直接検証する
	// （GetErrorHandled には依存しない / Set/Get のテストを独立にする）。
	ctx := SetErrorHandled(context.Background(), true)

	val := ctx.Value(errorhandledKey)
	v, ok := val.(bool)
	assert.True(t, ok)
	assert.Equal(t, true, v)
}

func TestGetErrorHandled(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("標準コンテキストから取得できる", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			ctx = SetErrorHandled(ctx, true)

			val, ok := GetErrorHandled(ctx)
			assert.True(t, ok)
			assert.Equal(t, true, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			ctx := context.Background()
			val, ok := GetErrorHandled(ctx)
			assert.False(t, ok)
			assert.Equal(t, false, val)
		})
	})
}

func TestSetErrorHandledToEcho(t *testing.T) {
	t.Parallel()

	t.Run("正常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoへ設定し取得できる", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			SetErrorHandledToEcho(c, true)
			val, ok := GetErrorHandledFromEcho(c)

			assert.True(t, ok)
			assert.Equal(t, true, val)
		})
	})

	t.Run("異常系", func(t *testing.T) {
		t.Parallel()
		t.Run("echoに値が無い場合はfalseを返す", func(t *testing.T) {
			t.Parallel()
			e := echo.New()
			ctx := context.Background()
			req := httptest.NewRequestWithContext(ctx, http.MethodGet, "/", nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			val, ok := GetErrorHandledFromEcho(c)
			assert.False(t, ok)
			assert.Equal(t, false, val)
		})
	})
}
