// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxHelper

import (
	"context"

	expectedErrors "boilerplate-go/internal/domain/expectederrors"

	"github.com/labstack/echo/v4"
)

type notfoundKeyType struct{}

var notfoundKey = notfoundKeyType{}

// --- std lib context ---

func SetNotFound(ctx context.Context, val expectedErrors.NotFoundCause) context.Context {
	return context.WithValue(ctx, notfoundKey, val)
}

func GetNotFound(ctx context.Context) (expectedErrors.NotFoundCause, bool) {
	val := ctx.Value(notfoundKey)
	if v, ok := val.(expectedErrors.NotFoundCause); ok {
		return v, true
	}
	return *new(expectedErrors.NotFoundCause), false
}

// --- echo.Context wrapper ---

func SetNotFoundToEcho(c echo.Context, val expectedErrors.NotFoundCause) {
	ctx := context.WithValue(c.Request().Context(), notfoundKey, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetNotFoundFromEcho(c echo.Context) (expectedErrors.NotFoundCause, bool) {
	val := c.Request().Context().Value(notfoundKey)
	if v, ok := val.(expectedErrors.NotFoundCause); ok {
		return v, true
	}
	return *new(expectedErrors.NotFoundCause), false
}
