// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxHelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/assert"
)

func TestNotFoundContext(t *testing.T) {
	t.Parallel()
	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = SetNotFound(ctx, "test-notfound")

		val, ok := GetNotFound(ctx)
		assert.True(t, ok)
		assert.Equal(t, "test-notfound", val)
	})

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		req := httptest.NewRequest(http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		SetNotFoundToEcho(c, "echo-notfound")
		val, ok := GetNotFoundFromEcho(c)

		assert.True(t, ok)
		assert.Equal(t, "echo-notfound", val)
	})
}
