// Package ctxhelper は、context.Context と echo.Context を操作するためのヘルパー関数を提供します。
// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"

	"boilerplate-go/internal/domain/expectederrors"

	"github.com/labstack/echo/v4"
)

type notfoundKeyType struct{}

var notfoundKey = notfoundKeyType{}

// --- std lib context ---

func SetNotFound(ctx context.Context, val expectederrors.NotFoundCause) context.Context {
	return context.WithValue(ctx, notfoundKey, val)
}

func GetNotFound(ctx context.Context) (expectederrors.NotFoundCause, bool) {
	val := ctx.Value(notfoundKey)
	if v, ok := val.(expectederrors.NotFoundCause); ok {
		return v, true
	}
	return *new(expectederrors.NotFoundCause), false
}

// --- echo.Context wrapper ---

func SetNotFoundToEcho(c echo.Context, val expectederrors.NotFoundCause) {
	ctx := context.WithValue(c.Request().Context(), notfoundKey, val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetNotFoundFromEcho(c echo.Context) (expectederrors.NotFoundCause, bool) {
	val := c.Request().Context().Value(notfoundKey)
	if v, ok := val.(expectederrors.NotFoundCause); ok {
		return v, true
	}
	return *new(expectederrors.NotFoundCause), false
}
