// Code generated by gen_ctxkey; DO NOT EDIT.
package ctxhelper

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"boilerplate-go/internal/domain/expectederrors"

	"github.com/labstack/echo/v4"
	"github.com/stretchr/testify/require"
)

func TestNotFoundContext(t *testing.T) {
	t.Parallel()
	t.Run("standard context", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		ctx = SetNotFound(ctx, *new(expectederrors.NotFoundCause))

		val, ok := GetNotFound(ctx)
		require.True(t, ok)
		require.Equal(t, *new(expectederrors.NotFoundCause), val)
	})

	t.Run("echo context", func(t *testing.T) {
		t.Parallel()
		e := echo.New()
		req := httptest.NewRequest(http.MethodGet, "/", nil)
		rec := httptest.NewRecorder()
		c := e.NewContext(req, rec)

		SetNotFoundToEcho(c, *new(expectederrors.NotFoundCause))
		val, ok := GetNotFoundFromEcho(c)

		require.True(t, ok)
		require.Equal(t, *new(expectederrors.NotFoundCause), val)
	})
}
