// Code generated by genctxkey; DO NOT EDIT.

package ctxhelper

import (
	"context"

	"github.com/labstack/echo/v5"
)

type recoveredKeyType struct{}

var recoveredKey = recoveredKeyType{}

// --- std lib context ---

func SetRecovered(ctx context.Context, val bool) context.Context {
	return context.WithValue(ctx, recoveredKey, val)
}

func GetRecovered(ctx context.Context) (bool, bool) {
	val := ctx.Value(recoveredKey)
	if v, ok := val.(bool); ok {
		return v, true
	}
	var zero bool
	return zero, false
}

// --- echo.Context wrapper（std lib 版へ委譲） ---

func SetRecoveredToEcho(c *echo.Context, val bool) {
	ctx := SetRecovered(c.Request().Context(), val)
	c.SetRequest(c.Request().WithContext(ctx))
}

func GetRecoveredFromEcho(c *echo.Context) (bool, bool) {
	return GetRecovered(c.Request().Context())
}
