name: Generate Docs on Merge

on:
  push:
    # branches:
    #   - release/** 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      ENV: ci
      DB: test
      DB_USER: postgres
      DB_PASSWORD: postgres-password

    services:
      database:
        image: postgres:17.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres-password
          POSTGRES_DB: test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup DB
        uses: ./.github/actions/setup-postgres
        with:
          db: ${{ env.DB }}
          user: ${{ env.DB_USER }}
          password: ${{ env.DB_PASSWORD }}
          init_sql: docker/database/sql/004-init-extensions-test-db.sql

      - name: Generate OpenAPI bundle
        run: make gen-bundle-oapi

      - name: Generate OpenAPI docs
        run: make gen-api-docs

      - name: Generate Portal Docs
        run: |
          make gen-portal-docs
          make gen-docs-json

      - name: Migrate
        run: go run cmd/main.go migrate-up --database ${{ env.DB }}

      - name: Seed Database
        run: go run cmd/main.go db-seed --database ${{ env.DB }}

      - name: Generate Test Repo Docs
        run: make gen-test-repo

      - name: Generate ER Diagram
        run: make gen-db-schema-ci

      - name: Detect changes
        id: diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_diff=true" >> $GITHUB_OUTPUT
          else
            echo "has_diff=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR
        id: cpr
        if: steps.diff.outputs.has_diff == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto update docs [skip ci]"
          branch: auto/docs-update/${{ github.ref_name }}
          base: ${{ github.ref_name }}
          title: "chore: auto update docs"
          body: |
            Auto-generated docs update.
          delete-branch: true
