name: CodeQL Scan

on:
  push:
    branches:
      - 'release/*'
      - develop
      - staging
      - production
    paths:
      - '.github/workflows/code-ql.yaml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '.github/workflows/code-ql.yaml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@7188fc363630916deb702c7fdcf4e481b751f97a # v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          category: '/language:go'
