name: DB Adapter Generation Check

on:
  pull_request:
    # paths:
    #   - '**/*.go'
    #   - 'go.mod'
    #   - 'go.sum'
    #   - '**/*.sql'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci-setup:
    uses: ./.github/workflows/golang-setup.yaml
    with:
      go-version: '1.24.4'
  db-adapter-gen-check:
    runs-on: ubuntu-latest
    env:
      ENV: ci
      SQLC_VER: v1.28.0
    services:
      database:
        image: postgres:17.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres-password
          POSTGRES_DB: test
          POSTGRES_INITDB_ARGS: "--encoding=UTF8"
          TZ: Asia/Tokyo
          PGTZ: Asia/Tokyo
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=20s
    steps:
      - name: Fetch & Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Database Table
        run: make ci-db-migrate-up
      - name: Seed Database
        run: make ci-db-seed
      - name: Generate SQLC Code
        run: make ci-gen-sqlc
      - name: Check diff
        run: |
          set -e
          git status --porcelain
          if ! git diff --quiet; then
            echo "## Generated files are out of date" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            git --no-pager diff --stat >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            git diff > codegen.patch
            echo "::error::Codegen drift detected. Please run generators locally and commit changes."
            exit 1
          fi
