name: Golang Setup
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.26.0'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch & Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: true
          cache: true
          cache-dependency-path: |
            **/go.sum
      - name: Download Dependencies
        run: go mod download
      - name: Check Go version
        run: go version
