name: Docker Image Scan Workflow

on:
  pull_request:
    branches: 
      - release/**
      - production
      - staging
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define image tag
        id: meta
        run: |
          IMAGE="local/${GITHUB_REPOSITORY#*/}/app:${GITHUB_SHA::7}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/server/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.image }}
          target: prd
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.meta.outputs.image }}
          format: spdx-json
          artifact-name: sbom-spdx.json
          upload-artifact: true

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ steps.meta.outputs.image }}
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
