name: OpenAPI Lint

on:
  pull_request:
    paths:
      - 'openapi/**'
      - 'redocly.yaml'
      - '.makefiles/openapi/**'
      - '.github/workflows/oapi-lint.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  oapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run redocly lint
        run: make lint-oapi
