// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock/mock_provider.go -package=mock_loggingdb
//

// Package mock_loggingdb is a generated GoMock package.
package mock_loggingdb

import (
	config "boilerplate-go/internal/config"
	driver "boilerplate-go/internal/infrastructure/rdb/driver"
	logging "boilerplate-go/internal/logging"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBProvider is a mock of DBProvider interface.
type MockDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDBProviderMockRecorder
	isgomock struct{}
}

// MockDBProviderMockRecorder is the mock recorder for MockDBProvider.
type MockDBProviderMockRecorder struct {
	mock *MockDBProvider
}

// NewMockDBProvider creates a new mock instance.
func NewMockDBProvider(ctrl *gomock.Controller) *MockDBProvider {
	mock := &MockDBProvider{ctrl: ctrl}
	mock.recorder = &MockDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBProvider) EXPECT() *MockDBProviderMockRecorder {
	return m.recorder
}

// DBConfig mocks base method.
func (m *MockDBProvider) DBConfig() *config.DatabaseConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBConfig")
	ret0, _ := ret[0].(*config.DatabaseConfig)
	return ret0
}

// DBConfig indicates an expected call of DBConfig.
func (mr *MockDBProviderMockRecorder) DBConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBConfig", reflect.TypeOf((*MockDBProvider)(nil).DBConfig))
}

// LogFields mocks base method.
func (m *MockDBProvider) LogFields() logging.LogFieldBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogFields")
	ret0, _ := ret[0].(logging.LogFieldBuilder)
	return ret0
}

// LogFields indicates an expected call of LogFields.
func (mr *MockDBProviderMockRecorder) LogFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogFields", reflect.TypeOf((*MockDBProvider)(nil).LogFields))
}

// Logger mocks base method.
func (m *MockDBProvider) Logger() logging.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(logging.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockDBProviderMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockDBProvider)(nil).Logger))
}

// NewLoggingDB mocks base method.
func (m *MockDBProvider) NewLoggingDB(ctx context.Context) driver.DBTX {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLoggingDB", ctx)
	ret0, _ := ret[0].(driver.DBTX)
	return ret0
}

// NewLoggingDB indicates an expected call of NewLoggingDB.
func (mr *MockDBProviderMockRecorder) NewLoggingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLoggingDB", reflect.TypeOf((*MockDBProvider)(nil).NewLoggingDB), ctx)
}
