// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock/mock_provider.go -package=mock_loggingdb
//

// Package mock_loggingdb is a generated GoMock package.
package mock_loggingdb

import (
	context "context"
	driver "go-boilerplate/internal/infrastructure/rdb/driver"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBProvider is a mock of DBProvider interface.
type MockDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDBProviderMockRecorder
	isgomock struct{}
}

// MockDBProviderMockRecorder is the mock recorder for MockDBProvider.
type MockDBProviderMockRecorder struct {
	mock *MockDBProvider
}

// NewMockDBProvider creates a new mock instance.
func NewMockDBProvider(ctrl *gomock.Controller) *MockDBProvider {
	mock := &MockDBProvider{ctrl: ctrl}
	mock.recorder = &MockDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBProvider) EXPECT() *MockDBProviderMockRecorder {
	return m.recorder
}

// NewLoggingDB mocks base method.
func (m *MockDBProvider) NewLoggingDB(ctx context.Context) driver.DBTX {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLoggingDB", ctx)
	ret0, _ := ret[0].(driver.DBTX)
	return ret0
}

// NewLoggingDB indicates an expected call of NewLoggingDB.
func (mr *MockDBProviderMockRecorder) NewLoggingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLoggingDB", reflect.TypeOf((*MockDBProvider)(nil).NewLoggingDB), ctx)
}
